import { resolveProjectAccess } from '@/core/session';
import { readV2Content } from '@/core/onboarding-data';
import { uploadMediaAction } from '../actions';

type StoredMedia={url?:unknown;path?:unknown};
const mediaUrl=(value:unknown)=>value&&typeof value==='object'&&'url' in value?String((value as StoredMedia).url||''):'';
const url=(o:Record<string,unknown>,k:string)=>mediaUrl(o[k]);
export default async function MediaPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{saved?:string}>}){
 const {slug}=await params,{saved}=await searchParams,{project}=await resolveProjectAccess(slug),data=await readV2Content(project.id);
 const gallery=(Array.isArray(data.media.gallery)?data.media.gallery:[]).map(mediaUrl).filter(Boolean).slice(-12),portfolio=project.segment==='portfolio',fitness=project.segment==='personal-trainer',logo=url(data.media,'logo')||(portfolio?url(data.media,'profile'):''),hero=url(data.media,'hero'),heroVideo=url(data.media,'hero_video');
 return <div className="editor-page"><header><span className="eyebrow dark-text">MÍDIA</span><h1>Biblioteca visual.</h1><p>Gerencie a mídia usada pelos modelos. Salvar atualiza somente o rascunho; publique depois de conferir no Preview.</p></header>{saved&&<div className="notice success"><strong>Mídia salva apenas no rascunho.</strong> Confira no Preview e publique quando estiver tudo certo.</div>}<form action={uploadMediaAction} className="form-stack"><input type="hidden" name="slug" value={project.slug}/><section className="editor-section"><div className="upload-grid"><label className="upload-card"><strong>{portfolio?'Foto de perfil / logo':'Logo'}</strong>{logo&&<img src={logo} alt={portfolio?'Foto de perfil atual':'Logo atual'} loading="lazy" decoding="async"/>}<span>Enviar nova imagem</span><input name="logo" type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label><label className="upload-card"><strong>Imagem principal / poster</strong>{hero&&<img src={hero} alt="Imagem principal atual" loading="lazy" decoding="async"/>}<span>Enviar nova imagem</span><input name="heroImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label></div>{fitness&&<div className="upload-card"><strong>Vídeo do hero</strong><span>{heroVideo?'Vídeo atual configurado. Envie outro para substituir.':'Opcional. Se vazio, o site usa a imagem principal.'}</span>{heroVideo&&<video src={heroVideo} controls preload="metadata" playsInline style={{width:'100%',maxHeight:320,borderRadius:12}}/>}<small>MP4 ou WebM, até 50 MB. A imagem principal funciona como poster/fallback.</small><label className="field"><span>Selecionar vídeo</span><input name="heroVideo" type="file" accept="video/mp4,video/webm"/></label></div>}<label className="upload-card"><strong>Adicionar à galeria</strong><span>Selecione várias imagens. O CMS mantém até 12 e os templates usam as imagens conforme o layout.</span><input name="gallery" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple/></label>{gallery.length>0&&<div className="media-gallery">{gallery.map((src,i)=><img key={`${src}-${i}`} src={src} alt={`Galeria ${i+1}`} loading="lazy" decoding="async"/>)}</div>}</section><div className="sticky-save"><button className="action primary">Salvar mídia no rascunho</button></div></form></div>;
}
