import { resolveProjectAccess } from '@/core/session';
import { readV2Content } from '@/core/onboarding-data';
import { uploadMediaAction } from '../actions';

type StoredMedia={url?:unknown;path?:unknown};
const mediaUrl=(value:unknown)=>value&&typeof value==='object'&&'url' in value?String((value as StoredMedia).url||''):'';
const url=(o:Record<string,unknown>,k:string)=>mediaUrl(o[k]);
function ImageSlot({name,label,current,help}:{name:string;label:string;current:string;help?:string}){return <label className="upload-card"><strong>{label}</strong>{current&&<img src={current} alt={`${label} atual`} loading="lazy" decoding="async"/>}{help&&<small>{help}</small>}<span>{current?'Substituir imagem':'Selecionar imagem'}</span><input name={name} type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label>}
export default async function MediaPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{saved?:string}>}){
 const {slug}=await params,{saved}=await searchParams,{project}=await resolveProjectAccess(slug),data=await readV2Content(project.id);
 const gallery=(Array.isArray(data.media.gallery)?data.media.gallery:[]).map(mediaUrl).filter(Boolean).slice(-12),portfolio=project.segment==='portfolio',fitness=project.segment==='personal-trainer',logo=url(data.media,'logo')||(portfolio?url(data.media,'profile'):''),hero=url(data.media,'hero'),heroVideo=url(data.media,'hero_video');
 const performanceSlots=fitness?[['performanceEvidence','Foto dos números / prova','performance_evidence'],['performanceService1','Foto do serviço 1','performance_service_1'],['performanceService2','Foto do serviço 2','performance_service_2'],['performanceService3','Foto do serviço 3','performance_service_3'],['performanceService4','Foto do serviço 4','performance_service_4'],['performanceTrainer','Foto do treinador / sobre','performance_trainer']] as const:[];
 return <div className="editor-page"><header><span className="eyebrow dark-text">MÍDIA</span><h1>Biblioteca visual.</h1><p>Cada imagem importante possui uma função própria. Alterar o hero não substitui mais automaticamente as fotografias das demais seções.</p></header>{saved&&<div className="notice success"><strong>Mídia salva apenas no rascunho.</strong> Confira no Preview e publique quando estiver tudo certo.</div>}<form action={uploadMediaAction} className="form-stack"><input type="hidden" name="slug" value={project.slug}/><section className="editor-section"><h2>Identidade e hero</h2><div className="upload-grid"><ImageSlot name="logo" label={portfolio?'Foto de perfil / logo':'Logo'} current={logo}/><ImageSlot name="heroImage" label="Imagem principal / poster" current={hero} help="Usada somente no hero e como poster do vídeo."/></div>{fitness&&<div className="upload-card"><strong>Vídeo do hero</strong><span>{heroVideo?'Vídeo atual configurado. Envie outro para substituir.':'Opcional. Se vazio, o hero usa a imagem principal.'}</span>{heroVideo&&<video src={heroVideo} controls preload="metadata" playsInline style={{width:'100%',maxHeight:320,borderRadius:12}}/>}<small>MP4 ou WebM, até 50 MB. A imagem principal funciona como poster/fallback.</small><label className="field"><span>Selecionar vídeo</span><input name="heroVideo" type="file" accept="video/mp4,video/webm"/></label></div>}</section>{fitness&&<section className="editor-section"><span className="eyebrow dark-text">PERFORMANCE</span><h2>Fotos por seção</h2><p>Estas posições são independentes. Se uma estiver vazia, o template pode usar uma imagem de demonstração no Preview, mas nunca troca as outras quando você altera o hero.</p><div className="upload-grid">{performanceSlots.map(([name,label,key])=><ImageSlot key={name} name={name} label={label} current={url(data.media,key)}/>)}</div></section>}<section className="editor-section"><h2>Galeria / histórias</h2><label className="upload-card"><strong>Adicionar à galeria</strong><span>Selecione várias imagens. A galeria é usada para histórias/resultados e não como fonte automática das demais fotos do template.</span><input name="gallery" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple/></label>{gallery.length>0&&<div className="media-gallery">{gallery.map((src,i)=><img key={`${src}-${i}`} src={src} alt={`Galeria ${i+1}`} loading="lazy" decoding="async"/>)}</div>}</section><div className="sticky-save"><button className="action primary">Salvar mídia no rascunho</button></div></form></div>;
}
