import Link from 'next/link';
import { redirect } from 'next/navigation';
import { resolveProjectAccess } from '@/core/session';
import { onboardingLabels, onboardingPath, orderedOnboardingSteps } from '@/core/onboarding';
import { readV2Content } from '@/core/onboarding-data';
import { segments } from '@/core/segments';
import type { OnboardingStep } from '@/core/domain';
import { saveSetupStep, publishOnboardingProject } from './actions';

const steps=new Set<OnboardingStep>(['account','template','identity','content','media','appearance','contact','domain','review','completed']);
const value=(obj:Record<string,unknown>,key:string)=>String(obj[key]??'');

export default async function SetupPage({params}:{params:Promise<{slug:string;step:string}>}){
  const {slug,step}=await params;const access=await resolveProjectAccess(slug);const requested=steps.has(step as OnboardingStep)?step as OnboardingStep:access.project.onboardingStep;
  if(access.role!=='owner'&&requested!==access.project.onboardingStep)redirect(onboardingPath(access.project.onboardingStep,access.project.slug));if(requested==='completed')redirect(`/dashboard/${encodeURIComponent(access.project.slug)}`);
  const data=await readV2Content(access.project.id),segment=segments[access.project.segment],currentIndex=orderedOnboardingSteps.indexOf(requested);
  const common=<><input type="hidden" name="slug" value={access.project.slug}/><input type="hidden" name="step" value={requested}/></>;
  let body:React.ReactNode;

  if(requested==='account') body=<form action={saveSetupStep} className="form-stack">{common}<div className="welcome-box"><strong>Olá! Seu projeto já está pronto para configurar.</strong><p>Você vai escolher o visual, preencher as informações, enviar fotos e definir o endereço. Pode abrir o Preview durante o processo.</p></div><button className="action primary">Começar configuração →</button></form>;
  else if(requested==='template') body=<form action={saveSetupStep} className="form-stack">{common}<div className="template-grid">{segment.templates.map((template,index)=><label className={`template-option ${template.status==='planned'?'disabled':''}`} key={template.key}><input type="radio" name="templateKey" value={template.key} defaultChecked={access.project.templateKey===template.key||(!access.project.templateKey&&index===0)} disabled={template.status==='planned'}/><div className="template-preview"><span>{template.status==='planned'?'EM BREVE':template.status==='legacy'?'LEGADO':'DISPONÍVEL'}</span></div><strong>{template.name}</strong><p>{template.description}</p></label>)}</div><button className="action primary">Usar este modelo →</button></form>;
  else if(requested==='identity') body=<form action={saveSetupStep} className="form-stack">{common}<div className="form-grid"><label className="field"><span>Nome exibido</span><input name="name" defaultValue={value(data.identity,'name')||access.project.name} required/></label><label className="field"><span>Localização</span><input name="location" defaultValue={value(data.identity,'location')} placeholder="Ibitinga - SP"/></label></div><label className="field"><span>Frase curta / posicionamento</span><input name="tagline" defaultValue={value(data.identity,'tagline')} placeholder="O que você faz em uma frase"/></label><label className="field"><span>Descrição</span><textarea name="description" rows={4} defaultValue={value(data.identity,'description')} placeholder="Uma apresentação curta do negócio ou profissional."/></label><button className="action primary">Salvar e continuar →</button></form>;
  else if(requested==='content') body=<form action={saveSetupStep} className="form-stack">{common}<label className="field"><span>Título principal</span><textarea name="hero_title" rows={2} defaultValue={value(data.content,'hero_title')} placeholder="A principal promessa do site"/></label><label className="field"><span>Texto de apoio</span><textarea name="hero_text" rows={3} defaultValue={value(data.content,'hero_text')}/></label><div className="form-grid"><label className="field"><span>Oferta / serviço principal</span><textarea name="primary_offer" rows={4} defaultValue={value(data.content,'primary_offer')}/></label><label className="field"><span>Provas / diferenciais</span><textarea name="proof" rows={4} defaultValue={value(data.content,'proof')} placeholder="Resultados, diferenciais ou motivos para confiar"/></label></div><label className="field"><span>Sobre</span><textarea name="about" rows={5} defaultValue={value(data.content,'about')}/></label><label className="field"><span>Informações adicionais</span><textarea name="extra_notes" rows={4} defaultValue={value(data.content,'extra_notes')} placeholder="Detalhes que serão organizados no template do segmento"/></label><button className="action primary">Salvar e continuar →</button></form>;
  else if(requested==='media') body=<form action={saveSetupStep} className="form-stack">{common}<div className="upload-grid"><label className="upload-card"><strong>Logo</strong><span>PNG, JPG, WebP ou SVG · até 10 MB</span><input name="logo" type="file" accept="image/*"/></label><label className="upload-card"><strong>Imagem principal</strong><span>Use uma foto horizontal de boa qualidade.</span><input name="heroImage" type="file" accept="image/*"/></label></div><p className="help">Arquivos enviados anteriormente são preservados caso você avance sem escolher uma nova imagem.</p><button className="action primary">Salvar fotos e continuar →</button></form>;
  else if(requested==='appearance') body=<form action={saveSetupStep} className="form-stack">{common}<div className="form-grid"><label className="field"><span>Cor de destaque</span><input name="accent" type="color" defaultValue={value(data.appearance,'accent')||'#d9ff43'}/></label><label className="field"><span>Escala dos textos</span><select name="scale" defaultValue={value(data.appearance,'scale')||'normal'}><option value="compact">Compacta</option><option value="normal">Padrão</option><option value="large">Grande</option></select></label><label className="field"><span>Fonte dos títulos</span><select name="heading_font" defaultValue={value(data.appearance,'heading_font')||'Montserrat'}><option>Montserrat</option><option>Manrope</option><option>Fraunces</option><option>Playfair Display</option></select></label><label className="field"><span>Fonte dos textos</span><select name="body_font" defaultValue={value(data.appearance,'body_font')||'DM Sans'}><option>DM Sans</option><option>Inter</option><option>Manrope</option><option>Montserrat</option></select></label><label className="field"><span>Alinhamento</span><select name="alignment" defaultValue={value(data.appearance,'alignment')||'left'}><option value="left">Esquerda</option><option value="center">Centralizado</option><option value="right">Direita</option></select></label><label className="field"><span>Espaçamento</span><select name="density" defaultValue={value(data.appearance,'density')||'normal'}><option value="compact">Compacto</option><option value="normal">Padrão</option><option value="airy">Espaçoso</option></select></label></div><p className="help">O template continua controlando os limites seguros de responsividade e proporção.</p><button className="action primary">Salvar aparência →</button></form>;
  else if(requested==='contact') body=<form action={saveSetupStep} className="form-stack">{common}<div className="form-grid"><label className="field"><span>WhatsApp</span><input name="whatsapp" defaultValue={value(data.contact,'whatsapp')}/></label><label className="field"><span>Telefone</span><input name="phone" defaultValue={value(data.contact,'phone')}/></label><label className="field"><span>E-mail</span><input type="email" name="email" defaultValue={value(data.contact,'email')}/></label><label className="field"><span>Instagram</span><input name="instagram" defaultValue={value(data.contact,'instagram')} placeholder="@perfil ou URL"/></label></div><label className="field"><span>Endereço</span><input name="address" defaultValue={value(data.contact,'address')}/></label><label className="field"><span>Horários / observações</span><textarea name="hours" rows={3} defaultValue={value(data.contact,'hours')}/></label><button className="action primary">Salvar contato →</button></form>;
  else if(requested==='domain') body=<form action={saveSetupStep} className="form-stack">{common}<div className="native-domain"><span>Seu endereço WebAppCap</span><div><input name="nativeSubdomain" defaultValue={access.project.slug}/><strong>.webappcap.com.br</strong></div><small>O subdomínio WebAppCap é ativado automaticamente.</small></div><label className="field"><span>Domínio próprio (opcional)</span><input name="customDomain" placeholder="meusite.com.br"/><small>Domínio próprio será marcado como pendente até a validação DNS.</small></label><button className="action primary">Salvar endereço →</button></form>;
  else body=<div className="form-stack"><div className="review-grid"><article><span>Segmento</span><strong>{segment.name}</strong></article><article><span>Modelo</span><strong>{segment.templates.find(t=>t.key===access.project.templateKey)?.name||'Não escolhido'}</strong></article><article><span>Identidade</span><strong>{value(data.identity,'name')||access.project.name}</strong></article><article><span>Contato</span><strong>{value(data.contact,'whatsapp')||value(data.contact,'email')||'Não informado'}</strong></article></div><p className="help">Revise no Preview. A publicação encerra o onboarding e, nos próximos acessos, abre diretamente o Dashboard.</p><form action={publishOnboardingProject}>{common}<button className="action primary">Publicar site</button></form></div>;

  return <main className="setup-shell"><header className="setup-top"><Link href={access.role==='owner'?`/owner/projects/${access.project.slug}`:'/projects'} className="text-link">← Sair da configuração</Link><div className="setup-actions"><Link className="action secondary" href={`/preview/${encodeURIComponent(access.project.slug)}`} target="_blank">Preview ↗</Link></div></header><div className="progress">{orderedOnboardingSteps.filter(s=>s!=='completed').map((item,index)=><div key={item} className={index<currentIndex?'done':index===currentIndex?'active':''}><span>{index+1}</span><small>{onboardingLabels[item]}</small></div>)}</div><section className="setup-card"><span className="eyebrow">{segment.name} · {onboardingLabels[requested]}</span><h1>{requested==='review'?'Tudo pronto para revisar.':requested==='template'?'Escolha o estilo do seu site.':access.project.name}</h1><p>{requested==='template'?`Você verá apenas modelos criados para ${segment.name}. O conteúdo continuará o mesmo se futuramente trocar de modelo.`:'Preencha o essencial agora. Você poderá alterar tudo novamente depois no Dashboard.'}</p>{body}</section></main>
}
