import Link from 'next/link';
import { redirect } from 'next/navigation';
import { resolveProjectAccess } from '@/core/session';
import { onboardingLabels,onboardingPath,orderedOnboardingSteps } from '@/core/onboarding';
import { readV2Content } from '@/core/onboarding-data';
import { segments } from '@/core/segments';
import { sectionsForSegment } from '@/core/content-schema';
import { contractForTemplate } from '@/templates/contracts';
import type { OnboardingStep } from '@/core/domain';
import { RepeatableSections } from './repeatable-sections';
import { saveSetupStep,publishOnboardingProject } from './actions';
const steps=new Set<OnboardingStep>(['account','template','identity','content','media','appearance','contact','domain','review','completed']);const value=(o:Record<string,unknown>,k:string)=>String(o[k]??'');
export default async function SetupPage({params}:{params:Promise<{slug:string;step:string}>}){
 const {slug,step}=await params,access=await resolveProjectAccess(slug),requested=steps.has(step as OnboardingStep)?step as OnboardingStep:access.project.onboardingStep,requestedIndex=orderedOnboardingSteps.indexOf(requested),maxIndex=orderedOnboardingSteps.indexOf(access.project.onboardingStep);if(access.role!=='owner'&&requestedIndex>maxIndex)redirect(onboardingPath(access.project.onboardingStep,access.project.slug));if(requested==='completed')redirect(`/dashboard/${encodeURIComponent(access.project.slug)}`);
 const data=await readV2Content(access.project.id),segment=segments[access.project.segment],contract=contractForTemplate(access.project.templateKey),definitions=sectionsForSegment(access.project.segment),common=<><input type="hidden" name="slug" value={access.project.slug}/><input type="hidden" name="step" value={requested}/></>;let body:React.ReactNode;
 if(requested==='account')body=<form action={saveSetupStep} className="form-stack">{common}<div className="welcome-box"><strong>Vamos montar primeiro o perfil do seu projeto.</strong><p>O tipo de site já foi definido pela WebAppCap. Primeiro reunimos informações que funcionam em qualquer modelo; depois você escolhe a experiência visual e pode completar o site.</p></div><button className="action primary">Começar →</button></form>;
 else if(requested==='identity')body=<form action={saveSetupStep} className="form-stack">{common}<div className="form-grid"><label className="field"><span>Nome exibido</span><input name="name" defaultValue={value(data.identity,'name')||access.project.name} required/></label><label className="field"><span>Cidade / região</span><input name="location" defaultValue={value(data.identity,'location')}/></label></div><label className="field"><span>Frase curta / posicionamento</span><input name="tagline" defaultValue={value(data.identity,'tagline')}/></label><label className="field"><span>Apresentação</span><textarea name="description" rows={4} defaultValue={value(data.identity,'description')}/></label><button className="action primary">Salvar perfil →</button></form>;
 else if(requested==='content')body=<form action={saveSetupStep} className="form-stack">{common}<div className="welcome-box"><strong>Conteúdo essencial + blocos reutilizáveis</strong><p>Os primeiros campos servem para qualquer modelo. Abaixo você pode adicionar, remover e reordenar itens das seções disponíveis para este tipo de site.</p></div><label className="field"><span>Título principal</span><textarea name="hero_title" rows={2} defaultValue={value(data.content,'hero_title')}/></label><label className="field"><span>Texto de apoio</span><textarea name="hero_text" rows={3} defaultValue={value(data.content,'hero_text')}/></label><div className="form-grid"><label className="field"><span>Principal oferta / objetivo</span><textarea name="primary_offer" rows={4} defaultValue={value(data.content,'primary_offer')}/></label><label className="field"><span>Principal diferencial / prova</span><textarea name="proof" rows={4} defaultValue={value(data.content,'proof')}/></label></div><label className="field"><span>Sobre</span><textarea name="about" rows={4} defaultValue={value(data.content,'about')}/></label><label className="field"><span>Observações adicionais</span><textarea name="extra_notes" rows={3} defaultValue={value(data.content,'extra_notes')}/></label><RepeatableSections definitions={definitions} initial={data.content}/><button className="action primary">Salvar conteúdo →</button></form>;
 else if(requested==='contact')body=<form action={saveSetupStep} className="form-stack">{common}<div className="form-grid"><label className="field"><span>WhatsApp</span><input name="whatsapp" defaultValue={value(data.contact,'whatsapp')}/></label><label className="field"><span>Telefone</span><input name="phone" defaultValue={value(data.contact,'phone')}/></label><label className="field"><span>E-mail</span><input type="email" name="email" defaultValue={value(data.contact,'email')}/></label><label className="field"><span>Instagram</span><input name="instagram" defaultValue={value(data.contact,'instagram')}/></label></div><label className="field"><span>Endereço</span><input name="address" defaultValue={value(data.contact,'address')}/></label><label className="field"><span>Horários / observações</span><textarea name="hours" rows={3} defaultValue={value(data.contact,'hours')}/></label><button className="action primary">Salvar contato →</button></form>;
 else if(requested==='media')body=<form action={saveSetupStep} className="form-stack">{common}<div className="upload-grid"><label className="upload-card"><strong>Logo</strong><span>JPG, PNG, WebP ou GIF · até 10 MB</span><input name="logo" type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label><label className="upload-card"><strong>Imagem principal</strong><span>Escolha uma imagem forte e de boa qualidade.</span><input name="heroImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label></div><label className="upload-card"><strong>Galeria</strong><span>Até 12 imagens são preservadas.</span><input name="gallery" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple/></label><button className="action primary">Salvar mídia →</button></form>;
 else if(requested==='template')body=<form action={saveSetupStep} className="form-stack">{common}<div className="welcome-box"><strong>Agora escolha como seu conteúdo será apresentado.</strong><p>Os modelos abaixo pertencem ao tipo de site definido pelo administrador. Seu perfil e conteúdo não serão perdidos ao trocar de modelo.</p></div><div className="template-grid">{segment.templates.map((template,index)=><label className={`template-option ${template.status==='planned'?'disabled':''}`} key={template.key}><input type="radio" name="templateKey" value={template.key} defaultChecked={access.project.templateKey===template.key||(!access.project.templateKey&&index===0)} disabled={template.status==='planned'}/><div className="template-preview"><span>{template.status==='planned'?'EM BREVE':'DISPONÍVEL'}</span></div><strong>{template.name}</strong><p>{template.description}</p></label>)}</div><button className="action primary">Usar este modelo →</button></form>;
 else if(requested==='appearance')body=<form action={saveSetupStep} className="form-stack">{common}<div className="welcome-box"><strong>Personalização segura do modelo</strong><p>As opções abaixo são preservadas para compatibilidade. O contrato do modelo define quais delas realmente influenciam seu visual.</p>{contract&&<small>Modelo atual: {segment.templates.find(t=>t.key===access.project.templateKey)?.name} · cor {contract.appearance.accent?'suportada':'controlada pelo modelo'}.</small>}</div><div className="form-grid"><label className="field"><span>Cor de destaque</span><input name="accent" type="color" defaultValue={value(data.appearance,'accent')||'#d9ff43'}/></label><label className="field"><span>Escala</span><select name="scale" defaultValue={value(data.appearance,'scale')||'normal'}><option value="compact">Compacta</option><option value="normal">Padrão</option><option value="large">Grande</option></select></label><label className="field"><span>Fonte dos títulos</span><select name="heading_font" defaultValue={value(data.appearance,'heading_font')||'Montserrat'}><option>Montserrat</option><option>Manrope</option><option>Fraunces</option><option>Playfair Display</option></select></label><label className="field"><span>Fonte dos textos</span><select name="body_font" defaultValue={value(data.appearance,'body_font')||'DM Sans'}><option>DM Sans</option><option>Inter</option><option>Manrope</option><option>Montserrat</option></select></label><label className="field"><span>Alinhamento</span><select name="alignment" defaultValue={value(data.appearance,'alignment')||'left'}><option value="left">Esquerda</option><option value="center">Centralizado</option><option value="right">Direita</option></select></label><label className="field"><span>Espaçamento</span><select name="density" defaultValue={value(data.appearance,'density')||'normal'}><option value="compact">Compacto</option><option value="normal">Padrão</option><option value="airy">Espaçoso</option></select></label></div><button className="action primary">Salvar personalização →</button></form>;
 else if(requested==='domain')body=<form action={saveSetupStep} className="form-stack">{common}<div className="native-domain"><span>Seu endereço WebAppCap</span><div><input name="nativeSubdomain" defaultValue={access.project.slug}/><strong>.webappcap.com.br</strong></div></div><label className="field"><span>Domínio próprio (opcional)</span><input name="customDomain" placeholder="meusite.com.br"/></label><button className="action primary">Salvar endereço →</button></form>;
 else body=<div className="form-stack"><div className="review-grid"><article><span>Tipo do site</span><strong>{segment.name}</strong></article><article><span>Modelo</span><strong>{segment.templates.find(t=>t.key===access.project.templateKey)?.name||'Não escolhido'}</strong></article><article><span>Perfil</span><strong>{value(data.identity,'name')||access.project.name}</strong></article><article><span>Contato</span><strong>{value(data.contact,'whatsapp')||value(data.contact,'email')||'Não informado'}</strong></article></div><p className="help">Revise no Preview. Publicar encerra o onboarding; todo o conteúdo poderá continuar sendo alterado no Dashboard.</p><form action={publishOnboardingProject}>{common}<button className="action primary">Publicar site</button></form></div>;
 return <main className="setup-shell"><header className="setup-top"><Link href={access.role==='owner'?`/owner/projects/${access.project.slug}`:'/projects'} className="text-link">← Sair da configuração</Link><div className="setup-actions">{access.project.templateKey&&<Link className="action secondary" href={`/template-lab/${access.project.segment}/${encodeURIComponent(access.project.slug)}`} target="_blank">Comparar modelos ↗</Link>}<Link className="action secondary" href={`/preview/${encodeURIComponent(access.project.slug)}`} target="_blank">Preview ↗</Link></div></header><div className="progress">{orderedOnboardingSteps.filter(s=>s!=='completed').map((item,index)=>{const unlocked=access.role==='owner'||index<=maxIndex,className=index<maxIndex?'done':item===requested?'active':'';return unlocked?<Link href={`/setup/${encodeURIComponent(access.project.slug)}/${item}`} key={item} className={className}><span>{index+1}</span><small>{onboardingLabels[item]}</small></Link>:<div key={item}><span>{index+1}</span><small>{onboardingLabels[item]}</small></div>})}</div><section className="setup-card"><span className="eyebrow">{segment.name} · {onboardingLabels[requested]}</span><h1>{requested==='review'?'Tudo pronto para revisar.':requested==='template'?'Escolha o estilo do seu site.':access.project.name}</h1><p>{requested==='template'?'Seu conteúdo já está pronto para ser experimentado nos modelos disponíveis.':'O conteúdo pertence ao seu projeto, não ao template. Você poderá reutilizá-lo e ampliá-lo depois.'}</p>{body}</section></main>;
}
