'use client';
import { useState } from 'react';
import type { RepeatableSection } from '@/core/content-schema';

type Item=Record<string,string>;
export function RepeatableSections({definitions,initial}:{definitions:RepeatableSection[];initial:Record<string,unknown>}){
 const parse=(key:string):Item[]=>{const value=initial[key];if(Array.isArray(value))return value.filter(x=>x&&typeof x==='object') as Item[];return[]};
 const [sections,setSections]=useState<Record<string,Item[]>>(()=>Object.fromEntries(definitions.map(d=>[d.key,parse(d.key)])));
 const add=(definition:RepeatableSection)=>setSections(current=>({...current,[definition.key]:[...(current[definition.key]||[]),Object.fromEntries(definition.fields.map(f=>[f.key,'']))]}));
 const remove=(key:string,index:number)=>setSections(current=>({...current,[key]:(current[key]||[]).filter((_,i)=>i!==index)}));
 const move=(key:string,index:number,delta:number)=>setSections(current=>{const list=[...(current[key]||[])],target=index+delta;if(target<0||target>=list.length)return current;[list[index],list[target]]=[list[target],list[index]];return{...current,[key]:list}});
 const update=(key:string,index:number,field:string,value:string)=>setSections(current=>{const list=[...(current[key]||[])];list[index]={...list[index],[field]:value};return{...current,[key]:list}});
 return <div className="form-stack">{definitions.map(def=>{const items=sections[def.key]||[];return <section className="editor-section" key={def.key}><div style={{display:'flex',justifyContent:'space-between',gap:'1rem',alignItems:'start',flexWrap:'wrap'}}><div><strong>{def.label}</strong><p className="help" style={{margin:'.35rem 0 0'}}>{def.description}</p></div><button type="button" className="action secondary" onClick={()=>add(def)} disabled={Boolean(def.max&&items.length>=def.max)}>+ Adicionar item</button></div><input type="hidden" name={`section:${def.key}`} value={JSON.stringify(items)}/>{items.length===0?<p className="help">Nenhum item ainda. Esta seção pode ficar vazia.</p>:<div className="form-stack" style={{marginTop:'1rem'}}>{items.map((item,index)=><article key={index} style={{border:'1px solid rgba(17,17,17,.12)',borderRadius:14,padding:'1rem'}}><div style={{display:'flex',justifyContent:'space-between',gap:'.5rem',marginBottom:'.8rem'}}><strong>Item {index+1}</strong><div style={{display:'flex',gap:'.35rem'}}><button type="button" className="action secondary" onClick={()=>move(def.key,index,-1)} disabled={index===0}>↑</button><button type="button" className="action secondary" onClick={()=>move(def.key,index,1)} disabled={index===items.length-1}>↓</button><button type="button" className="action secondary" onClick={()=>remove(def.key,index)}>Remover</button></div></div><div className="form-grid">{def.fields.map(field=><label className="field" key={field.key}><span>{field.label}</span>{field.key==='description'||field.key==='text'||field.key==='answer'?<textarea rows={3} value={item[field.key]||''} onChange={e=>update(def.key,index,field.key,e.target.value)} placeholder={field.placeholder}/>:<input value={item[field.key]||''} onChange={e=>update(def.key,index,field.key,e.target.value)} placeholder={field.placeholder}/>}</label>)}</div></article>)}</div>}</section>})}</div>;
}
