'use client';
import { useState } from 'react';
import type { RepeatableSection } from '@/core/content-schema';

type Item=Record<string,string>;
const fieldLanguage=(key:string)=>key.endsWith('_pt')?'pt':key.endsWith('_en')?'en':undefined;
export function RepeatableSections({definitions,initial,collapsible=false,numberOffset=2}:{definitions:RepeatableSection[];initial:Record<string,unknown>;collapsible?:boolean;numberOffset?:number}){
 const parse=(key:string):Item[]=>{const value=initial[key];if(Array.isArray(value))return value.filter(x=>x&&typeof x==='object') as Item[];return[]};
 const [sections,setSections]=useState<Record<string,Item[]>>(()=>Object.fromEntries(definitions.map(d=>[d.key,parse(d.key)])));
 const add=(definition:RepeatableSection)=>setSections(current=>({...current,[definition.key]:[...(current[definition.key]||[]),Object.fromEntries(definition.fields.map(f=>[f.key,'']))]}));
 const remove=(key:string,index:number)=>setSections(current=>({...current,[key]:(current[key]||[]).filter((_,i)=>i!==index)}));
 const move=(key:string,index:number,delta:number)=>setSections(current=>{const list=[...(current[key]||[])],target=index+delta;if(target<0||target>=list.length)return current;[list[index],list[target]]=[list[target],list[index]];return{...current,[key]:list}});
 const update=(key:string,index:number,field:string,value:string)=>setSections(current=>{const list=[...(current[key]||[])];list[index]={...list[index],[field]:value};return{...current,[key]:list}});
 const multiline=(key:string)=>key.includes('description')||key==='text'||key==='answer'||key.startsWith('alt_');
 const fields=(def:RepeatableSection,items:Item[])=><><input type="hidden" name={`section:${def.key}`} value={JSON.stringify(items)}/>{items.length===0?<p className="help">Nenhum item ainda. Esta seção pode ficar vazia.</p>:<div className="form-stack">{items.map((item,index)=><article key={index} style={{border:'1px solid rgba(17,17,17,.12)',borderRadius:14,padding:'1rem'}}><div style={{display:'flex',justifyContent:'space-between',gap:'.5rem',marginBottom:'.8rem'}}><strong>Item {index+1}</strong><div style={{display:'flex',gap:'.35rem'}}><button type="button" className="action secondary" onClick={()=>move(def.key,index,-1)} disabled={index===0}>↑</button><button type="button" className="action secondary" onClick={()=>move(def.key,index,1)} disabled={index===items.length-1}>↓</button><button type="button" className="action secondary" onClick={()=>remove(def.key,index)}>Remover</button></div></div><div className="form-grid">{def.fields.map(field=><label className="field" data-language={fieldLanguage(field.key)} key={field.key}><span>{field.label}</span>{multiline(field.key)?<textarea rows={3} value={item[field.key]||''} onChange={e=>update(def.key,index,field.key,e.target.value)} placeholder={field.placeholder}/>:<input value={item[field.key]||''} onChange={e=>update(def.key,index,field.key,e.target.value)} placeholder={field.placeholder}/>}</label>)}</div></article>)}</div>}</>;
 return <div className="form-stack">{definitions.map((def,index)=>{const items=sections[def.key]||[],addButton=<button type="button" className="action secondary" onClick={()=>add(def)} disabled={Boolean(def.max&&items.length>=def.max)}>+ Adicionar item</button>;return collapsible?<details className="repeatable-section" id={`content-${def.key}`} data-number={String(index+numberOffset).padStart(2,'0')} key={def.key}><summary><span><strong>{def.label}</strong><small>{def.description} · {items.length} {items.length===1?'item':'itens'}</small></span></summary><div className="repeatable-body"><div style={{display:'flex',justifyContent:'flex-end',marginBottom:'.8rem'}}>{addButton}</div>{fields(def,items)}</div></details>:<section className="editor-section" key={def.key}><div style={{display:'flex',justifyContent:'space-between',gap:'1rem',alignItems:'start',flexWrap:'wrap'}}><div><strong>{def.label}</strong><p className="help" style={{margin:'.35rem 0 0'}}>{def.description}</p></div>{addButton}</div>{fields(def,items)}</section>})}</div>;
}
