-- WebAppCap Phase 8 — Analytics & Conversions
-- Execute once in the Supabase SQL Editor.

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  event_type text not null,
  event_label text,
  path text,
  referrer_host text,
  session_id text,
  occurred_at timestamptz not null default now(),
  constraint site_analytics_events_type_check check (event_type in ('page_view','contact_click','whatsapp_click','instagram_click','linkedin_click','email_click','cv_click','external_click')),
  constraint site_analytics_events_label_len check (event_label is null or char_length(event_label) <= 160),
  constraint site_analytics_events_path_len check (path is null or char_length(path) <= 500),
  constraint site_analytics_events_referrer_len check (referrer_host is null or char_length(referrer_host) <= 255),
  constraint site_analytics_events_session_len check (session_id is null or char_length(session_id) <= 100)
);

create index if not exists site_analytics_events_project_time_idx on public.site_analytics_events(project_id, occurred_at desc);
create index if not exists site_analytics_events_project_type_time_idx on public.site_analytics_events(project_id, event_type, occurred_at desc);

alter table public.site_analytics_events enable row level security;

drop policy if exists "analytics members can read" on public.site_analytics_events;
create policy "analytics members can read"
on public.site_analytics_events
for select
to authenticated
using (
  exists (
    select 1 from public.project_members pm
    where pm.project_id = site_analytics_events.project_id
      and pm.user_id = auth.uid()
      and lower(pm.role) in ('owner','admin')
  )
);

revoke all on public.site_analytics_events from anon, authenticated;
grant select on public.site_analytics_events to authenticated;

create or replace function public.webappcap_track_event(
  p_project_id uuid,
  p_event_type text,
  p_event_label text default null,
  p_path text default null,
  p_referrer_host text default null,
  p_session_id text default null
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_type not in ('page_view','contact_click','whatsapp_click','instagram_click','linkedin_click','email_click','cv_click','external_click') then
    return false;
  end if;

  if not exists (
    select 1 from public.projects p
    where p.id = p_project_id
      and p.is_published = true
  ) then
    return false;
  end if;

  insert into public.site_analytics_events(project_id,event_type,event_label,path,referrer_host,session_id)
  values (
    p_project_id,
    p_event_type,
    left(nullif(trim(p_event_label),''),160),
    left(nullif(trim(p_path),''),500),
    left(nullif(lower(trim(p_referrer_host)),''),255),
    left(nullif(trim(p_session_id),''),100)
  );
  return true;
end;
$$;

revoke all on function public.webappcap_track_event(uuid,text,text,text,text,text) from public;
grant execute on function public.webappcap_track_event(uuid,text,text,text,text,text) to anon, authenticated;

create or replace function public.webappcap_project_analytics(
  p_project_id uuid,
  p_days integer default 30
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30),365));
  v_since timestamptz := now() - make_interval(days => greatest(1, least(coalesce(p_days,30),365)));
  v_result jsonb;
begin
  if not exists (
    select 1 from public.project_members pm
    where pm.project_id = p_project_id
      and pm.user_id = auth.uid()
      and lower(pm.role) in ('owner','admin')
  ) then
    raise exception 'Sem permissão para visualizar analytics deste projeto.' using errcode='42501';
  end if;

  select jsonb_build_object(
    'days', v_days,
    'page_views', count(*) filter (where event_type='page_view'),
    'unique_sessions', count(distinct session_id) filter (where event_type='page_view' and session_id is not null),
    'conversions', count(*) filter (where event_type<>'page_view'),
    'converted_sessions', count(distinct session_id) filter (where event_type<>'page_view' and session_id is not null),
    'conversion_rate', case
      when count(distinct session_id) filter (where event_type='page_view' and session_id is not null) = 0 then 0
      else round(
        (count(distinct session_id) filter (where event_type<>'page_view' and session_id is not null))::numeric * 100
        / (count(distinct session_id) filter (where event_type='page_view' and session_id is not null)),
        2
      )
    end,
    'events', coalesce((
      select jsonb_agg(jsonb_build_object('event_type',event_type,'count',cnt) order by cnt desc)
      from (
        select event_type, count(*) cnt
        from public.site_analytics_events
        where project_id=p_project_id and occurred_at>=v_since
        group by event_type
      ) x
    ), '[]'::jsonb),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object('day',event_day,'page_views',page_views,'conversions',conversions) order by event_day)
      from (
        select occurred_at::date as event_day,
               count(*) filter (where event_type='page_view') as page_views,
               count(*) filter (where event_type<>'page_view') as conversions
        from public.site_analytics_events
        where project_id=p_project_id and occurred_at>=v_since
        group by occurred_at::date
      ) d
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(jsonb_build_object('host',referrer_host,'count',cnt) order by cnt desc)
      from (
        select coalesce(referrer_host,'Direto') referrer_host, count(*) cnt
        from public.site_analytics_events
        where project_id=p_project_id and occurred_at>=v_since and event_type='page_view'
        group by coalesce(referrer_host,'Direto')
        order by cnt desc
        limit 10
      ) r
    ), '[]'::jsonb)
  ) into v_result
  from public.site_analytics_events
  where project_id=p_project_id and occurred_at>=v_since;

  return coalesce(v_result, jsonb_build_object('days',v_days,'page_views',0,'unique_sessions',0,'conversions',0,'converted_sessions',0,'conversion_rate',0,'events','[]'::jsonb,'daily','[]'::jsonb,'referrers','[]'::jsonb));
end;
$$;

revoke all on function public.webappcap_project_analytics(uuid,integer) from public;
grant execute on function public.webappcap_project_analytics(uuid,integer) to authenticated;
