-- WebAppCap Phase 9 — Leads & lightweight CRM

create table if not exists public.site_leads (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  message text,
  source text not null default 'site_form',
  path text,
  session_id text,
  status text not null default 'new',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_leads_status_check check (status in ('new','contacted','qualified','won','lost')),
  constraint site_leads_name_len check (char_length(name) between 2 and 120),
  constraint site_leads_email_len check (email is null or char_length(email) <= 180),
  constraint site_leads_phone_len check (phone is null or char_length(phone) <= 60),
  constraint site_leads_message_len check (message is null or char_length(message) <= 3000),
  constraint site_leads_notes_len check (notes is null or char_length(notes) <= 5000)
);

create index if not exists site_leads_project_created_idx on public.site_leads(project_id, created_at desc);
create index if not exists site_leads_project_status_idx on public.site_leads(project_id, status, created_at desc);

alter table public.site_leads enable row level security;

drop policy if exists "lead managers can read" on public.site_leads;
create policy "lead managers can read"
on public.site_leads for select to authenticated
using (exists (
  select 1 from public.project_members pm
  where pm.project_id=site_leads.project_id
    and pm.user_id=auth.uid()
    and lower(pm.role) in ('owner','admin')
));

drop policy if exists "lead managers can update" on public.site_leads;
create policy "lead managers can update"
on public.site_leads for update to authenticated
using (exists (
  select 1 from public.project_members pm
  where pm.project_id=site_leads.project_id
    and pm.user_id=auth.uid()
    and lower(pm.role) in ('owner','admin')
))
with check (exists (
  select 1 from public.project_members pm
  where pm.project_id=site_leads.project_id
    and pm.user_id=auth.uid()
    and lower(pm.role) in ('owner','admin')
));

revoke all on public.site_leads from anon, authenticated;
grant select, update on public.site_leads to authenticated;

create or replace function public.webappcap_submit_lead(
  p_project_id uuid,
  p_name text,
  p_email text default null,
  p_phone text default null,
  p_message text default null,
  p_source text default 'site_form',
  p_path text default null,
  p_session_id text default null
) returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_id bigint;
  v_name text := left(trim(coalesce(p_name,'')),120);
  v_email text := left(nullif(lower(trim(coalesce(p_email,''))),''),180);
  v_phone text := left(nullif(trim(coalesce(p_phone,'')),''),60);
  v_message text := left(nullif(trim(coalesce(p_message,'')),''),3000);
  v_session text := left(nullif(trim(coalesce(p_session_id,'')),''),100);
begin
  if not exists (select 1 from public.projects p where p.id=p_project_id and p.is_published=true) then
    raise exception 'Projeto indisponível para captação de leads.' using errcode='22023';
  end if;
  if char_length(v_name) < 2 then
    raise exception 'Informe seu nome.' using errcode='22023';
  end if;
  if v_email is null and v_phone is null then
    raise exception 'Informe e-mail ou telefone.' using errcode='22023';
  end if;
  if v_email is not null and v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'E-mail inválido.' using errcode='22023';
  end if;
  if v_session is not null and exists (
    select 1 from public.site_leads
    where project_id=p_project_id and session_id=v_session
      and created_at > now() - interval '60 seconds'
      and coalesce(email,'')=coalesce(v_email,'')
      and coalesce(phone,'')=coalesce(v_phone,'')
  ) then
    raise exception 'Aguarde um momento antes de enviar novamente.' using errcode='22023';
  end if;

  insert into public.site_leads(project_id,name,email,phone,message,source,path,session_id)
  values (
    p_project_id,
    v_name,
    v_email,
    v_phone,
    v_message,
    left(coalesce(nullif(trim(p_source),''),'site_form'),80),
    left(nullif(trim(coalesce(p_path,'')),''),500),
    v_session
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.webappcap_submit_lead(uuid,text,text,text,text,text,text,text) from public;
grant execute on function public.webappcap_submit_lead(uuid,text,text,text,text,text,text,text) to anon, authenticated;
