'use server';
import {headers} from 'next/headers';
import {revalidatePath} from 'next/cache';
import {redirect} from 'next/navigation';
import {resolveProjectAccess} from '@/core/session';
import {can,normalizeRole} from '@/core/permissions';
import {createSupabaseServerClient} from '@/lib/supabase/server';

const base=async(slug:string)=>{const access=await resolveProjectAccess(slug);if(!can(access.role,'inviteMembers'))throw new Error('Sem permissão para gerenciar equipe.');return access};
const origin=async()=>{const h=await headers(),host=h.get('x-forwarded-host')||h.get('host');return `${h.get('x-forwarded-proto')||'https'}://${host}`};
export async function inviteMemberAction(formData:FormData){const slug=String(formData.get('slug')||''),access=await base(slug),email=String(formData.get('email')||'').trim().toLowerCase(),role=normalizeRole(formData.get('role'));if(!email||!role||role==='owner')throw new Error('Convite inválido.');const sb=await createSupabaseServerClient(),redirect_to=`${await origin()}/auth/callback?next=${encodeURIComponent(`/dashboard/${slug}`)}`;const q=await sb.functions.invoke('manage-project-member',{body:{project_id:access.project.id,action:'invite',email,role,redirect_to,invited_by:access.user.id}});if(q.error)throw q.error;const tracked=await sb.rpc('webappcap_record_member_inviter',{p_project_id:access.project.id,p_email:email});if(tracked.error&&tracked.error.code!=='PGRST202')throw tracked.error;revalidatePath(`/dashboard/${slug}/team`);redirect(`/dashboard/${encodeURIComponent(slug)}/team?invited=1`)}
export async function updateMemberAction(formData:FormData){const slug=String(formData.get('slug')||''),access=await base(slug),user_id=String(formData.get('user_id')||''),role=normalizeRole(formData.get('role'));if(!user_id||!role||role==='owner')throw new Error('Alteração inválida.');const sb=await createSupabaseServerClient(),q=await sb.functions.invoke('manage-project-member',{body:{project_id:access.project.id,action:'update_role',user_id,role}});if(q.error)throw q.error;revalidatePath(`/dashboard/${slug}/team`)}
export async function removeMemberAction(formData:FormData){const slug=String(formData.get('slug')||''),access=await base(slug),user_id=String(formData.get('user_id')||'');if(!user_id||user_id===access.user.id)redirect(`/dashboard/${encodeURIComponent(slug)}/team?removeError=self`);const sb=await createSupabaseServerClient();let targetData:{user_id:string;role:string;invited_by?:string|null}|null=null;const target=await sb.from('project_members').select('user_id,role,invited_by').eq('project_id',access.project.id).eq('user_id',user_id).maybeSingle();if(target.error?.code==='42703'){if(access.role==='admin')redirect(`/dashboard/${encodeURIComponent(slug)}/team?removeError=tracking`);const fallback=await sb.from('project_members').select('user_id,role').eq('project_id',access.project.id).eq('user_id',user_id).maybeSingle();if(fallback.error)throw fallback.error;targetData=fallback.data}else{if(target.error)throw target.error;targetData=target.data}if(!targetData||targetData.role==='owner')redirect(`/dashboard/${encodeURIComponent(slug)}/team?removeError=protected`);if(access.role==='admin'&&targetData.invited_by!==access.user.id)redirect(`/dashboard/${encodeURIComponent(slug)}/team?removeError=not-yours`);const q=await sb.functions.invoke('manage-project-member',{body:{project_id:access.project.id,action:'remove',user_id}});if(q.error)throw q.error;revalidatePath(`/dashboard/${slug}/team`);redirect(`/dashboard/${encodeURIComponent(slug)}/team?removed=1`)}
