import {redirect} from 'next/navigation';
import {resolveProjectAccess} from '@/core/session';
import {can} from '@/core/permissions';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {inviteMemberAction,removeMemberAction,updateMemberAction} from './actions';
import styles from './team.module.css';

type Member={user_id:string;email:string|null;role:string;created_at:string;invited_by?:string|null};
const roleName=(role:string)=>({owner:'Owner',admin:'Admin',editor:'Colaborador',viewer:'Visualizador'}[role]||role);

export default async function TeamPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{invited?:string;new?:string;removed?:string;removeError?:string;inviteError?:string}>}){
 const {slug}=await params,query=await searchParams,access=await resolveProjectAccess(slug);if(!can(access.role,'inviteMembers'))redirect(`/dashboard/${access.project.slug}`);
 const inviteConfigured=Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.RESEND_API_KEY&&process.env.WEBAPPCAP_FROM_EMAIL);
 const sb=await createSupabaseServerClient();let q=await sb.from('project_members').select('user_id,email,role,created_at,invited_by').eq('project_id',access.project.id).order('created_at');
 if(q.error?.code==='42703')q=await sb.from('project_members').select('user_id,email,role,created_at').eq('project_id',access.project.id).order('created_at') as typeof q;
 if(q.error)throw q.error;const members=(q.data||[]) as Member[];
 const errorMessage=query.inviteError==='config'?'Os convites ainda não estão configurados neste ambiente. É necessário habilitar a chave administrativa do Supabase e o serviço de e-mail.':query.inviteError==='email'?'O acesso não foi criado porque o e-mail com as credenciais não pôde ser entregue. Verifique a configuração de envio e tente novamente.':query.removeError==='not-yours'?'Admins só podem excluir pessoas que eles próprios convidaram.':query.removeError==='self'?'Você não pode excluir o próprio acesso.':query.removeError==='tracking'?'O controle de convites ainda precisa ser ativado antes de um admin excluir membros.':query.removeError?'Este acesso é protegido e não pode ser excluído.':'';
 return <div className="editor-page"><header><span className="eyebrow dark-text">EQUIPE</span><h1>Acessos do projeto</h1><p>O owner controla toda a equipe. Cada admin pode excluir somente as pessoas que ele mesmo convidou.</p></header>
  {query.invited?<div className="notice success">{query.new==='1'?'Acesso criado e enviado por e-mail com uma senha provisória. O convidado poderá alterá-la em Configurações.':'Acesso enviado por e-mail. Como esta pessoa já possuía uma conta, ela continuará usando a senha atual.'}</div>:null}{query.removed?<div className="notice success">Acesso removido.</div>:null}{errorMessage?<div className="notice">{errorMessage}</div>:null}
  <section className="editor-section"><h2>Membros</h2><p className={styles.rule}>O owner pode remover qualquer convidado. Admins não podem remover o owner, o próprio acesso ou pessoas convidadas por terceiros.</p><div className={styles.members}>{members.map(member=>{const isSelf=member.user_id===access.user.id,canRemove=member.role!=='owner'&&!isSelf&&(access.role==='owner'||member.invited_by===access.user.id);return <article className={styles.member} key={member.user_id}><div className={styles.identity}><strong>{member.email||'Usuário'}</strong><p className="help">{isSelf?'Você · ':''}{roleName(member.role)}</p></div><div className={styles.actions}>{member.role!=='owner'?<form action={updateMemberAction}><input type="hidden" name="slug" value={access.project.slug}/><input type="hidden" name="user_id" value={member.user_id}/><select name="role" defaultValue={member.role}><option value="admin">Admin</option><option value="editor">Colaborador</option><option value="viewer">Visualizador</option></select><button className="action secondary">Atualizar</button></form>:<span className={styles.role}>Owner</span>}{canRemove?<form action={removeMemberAction}><input type="hidden" name="slug" value={access.project.slug}/><input type="hidden" name="user_id" value={member.user_id}/><button className={styles.danger}>Excluir acesso</button></form>:null}</div></article>})}</div></section>
  <form action={inviteMemberAction} className="editor-section form-stack"><h2>Convidar pessoa</h2><p className="help">Novas contas recebem por e-mail uma senha provisória e o link para entrar. A senha pode ser trocada depois em Configurações.</p>{!inviteConfigured?<div className="notice">Convites por e-mail ainda não estão configurados neste ambiente. Nenhum acesso será criado até a configuração ser concluída.</div>:null}<input type="hidden" name="slug" value={access.project.slug}/><label className="field"><span>E-mail</span><input name="email" type="email" required disabled={!inviteConfigured}/></label><label className="field"><span>Acesso</span><select name="role" defaultValue="editor" disabled={!inviteConfigured}><option value="admin">Admin — conteúdo, aparência, equipe e publicação</option><option value="editor">Colaborador — conteúdo e fotos</option><option value="viewer">Visualizador — somente leitura</option></select></label><button className="action primary" disabled={!inviteConfigured}>Enviar convite</button></form>
 </div>;
}
