import Link from 'next/link';
import { requirePlatformOwner } from '@/core/session';
import { readRootDraft, rootValue } from '@/core/root-site';
import { publishRootAction, saveRootDraftAction } from './actions';
import styles from './root-editor.module.css';

const field=(draft:Record<string,string>,name:string,label:string,fallback:string,wide=false,area=false)=><label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{area?<textarea name={name} rows={3} defaultValue={rootValue(draft,name,fallback)}/>:<input name={name} defaultValue={rootValue(draft,name,fallback)}/>}</label>;

export default async function RootEditorPage({searchParams}:{searchParams:Promise<{saved?:string;published?:string}>}){
  await requirePlatformOwner();
  const query=await searchParams,{draft,publishedAt}=await readRootDraft();
  return <main className={styles.shell}><div className={styles.workspace}>
    <div className={styles.top}><Link href="/owner/projects">← Projetos</Link><div className={styles.actions}><Link className={styles.button} href="/owner/root/preview" target="_blank">Preview ↗</Link><a className={styles.button} href="https://www.webappcap.com.br" target="_blank" rel="noreferrer">Ver site ↗</a></div></div>
    <header className={styles.header}><div><span>PROJETO RAIZ</span><h1>WebAppCap</h1></div><p>Edite os textos institucionais. Salvar atualiza somente o Preview; Publicar envia o rascunho para a raiz.</p></header>
    {query.saved?<div className={styles.notice}>Rascunho salvo. Confira no Preview antes de publicar.</div>:null}
    {query.published?<div className={styles.notice}>Raiz publicada com sucesso.</div>:null}
    <form action={saveRootDraftAction} className={styles.form}>
      <section className={styles.section}><h2>Abertura</h2><div className={styles.grid}>{field(draft,'hero_eyebrow','Linha de contexto','Sites autorais · gestão simples')}{field(draft,'hero_title','Título','Seu trabalho merece um site à')}{field(draft,'hero_emphasis','Destaque','altura.')}{field(draft,'hero_description','Apresentação','A WebAppCap cria sites profissionais com personalidade, desempenho e um painel simples para você manter tudo atualizado.',true,true)}</div></section>
      <section className={styles.section}><h2>Movimento, processo e painel</h2><div className={styles.grid}>{field(draft,'marquee_items','Textos da faixa · um por linha','IDENTIDADE DIGITAL\nDESIGN RESPONSIVO\nPAINEL DE CONTEÚDO\nDOMÍNIO PRÓPRIO',true,true)}{field(draft,'process_title','Título do processo','Um caminho simples até o seu site.')}{field(draft,'process_description','Descrição do processo','Você não precisa entender de código, hospedagem ou configuração. A WebAppCap organiza o processo e deixa as decisões importantes nas suas mãos.',false,true)}{field(draft,'process_steps','Etapas · Título | descrição','Você conta sua ideia | Entendemos seu trabalho, seu público e o que o site precisa alcançar.\nCriamos sua presença | Conteúdo, identidade e estrutura são transformados em uma experiência feita para você.\nVocê revisa no preview | Confira cada detalhe em um endereço reservado antes de qualquer mudança ir ao ar.\nPublicamos e você assume | O site entra no seu domínio e o painel fica pronto para as próximas atualizações.',true,true)}{field(draft,'assurances','Diferenciais · um por linha','Identidade própria\nPainel simples\nPreview antes de publicar\nResponsivo por padrão',true,true)}{field(draft,'control_title','Título do painel','Mude o conteúdo.')}{field(draft,'control_emphasis','Destaque do painel','Não o código.')}{field(draft,'control_description','Descrição do painel','O painel reúne o que você precisa para manter o site vivo. Edite com tranquilidade, confira o resultado e escolha quando publicar.',true,true)}</div></section>
      <section className={styles.section}><h2>Projeto fundador</h2><div className={styles.grid}>{field(draft,'projects_title','Título','Primeiro usamos em casa.')}{field(draft,'project_name','Nome do projeto','Gabriel Capellari')}{field(draft,'projects_description','Introdução','O portfólio de Gabriel Capellari nasceu como site independente e se tornou o primeiro projeto completo construído sobre a base do WebAppCap.',true,true)}{field(draft,'project_description','Descrição do projeto','Um portfólio editorial que reúne trajetória, coberturas internacionais, trabalhos publicados e contato — com conteúdo gerenciado pelo próprio painel.',true,true)}{field(draft,'portfolio_url','Endereço do portfólio','https://capellari.webappcap.com.br',true)}</div></section>
      <section className={styles.section}><h2>Serviços, confiança e dúvidas</h2><div className={styles.grid}>{field(draft,'services_title','Título de serviços','O ponto de partida para a sua presença digital.')}{field(draft,'trust_title','Título de confiança','Clareza do primeiro contato à publicação.')}{field(draft,'services_description','Descrição de serviços','Cada site nasce de uma necessidade diferente. Escolha o formato mais próximo da sua ideia — o escopo final é sempre ajustado ao seu projeto.',false,true)}{field(draft,'trust_description','Descrição de confiança','Um bom site também depende de um bom processo. Estes são os compromissos que orientam cada projeto WebAppCap.',false,true)}{field(draft,'services','Serviços · Título | descrição | itens separados por ;','Portfólio profissional | Uma presença autoral para apresentar sua trajetória, projetos, serviços e formas de contato. | Identidade sob medida; Conteúdo organizado; Painel para atualizar\nSite institucional | Uma base sólida para negócios que precisam explicar o que fazem e transformar visitas em oportunidades. | Páginas estratégicas; Formulário de leads; Experiência responsiva\nLanding page | Uma página direta para divulgar um serviço, validar uma ideia ou conduzir uma campanha específica. | Mensagem objetiva; Chamada para ação; Publicação rápida',true,true)}{field(draft,'commitments','Compromissos · Selo | título | descrição','ESCOPO | Tudo definido antes | Você sabe o que será criado, quais conteúdos entram e como será a entrega.\nPREVIEW | Nada vai ao ar no escuro | O site fica disponível para revisão em um endereço reservado antes da publicação.\nCONTROLE | O conteúdo continua seu | Depois da entrega, o painel permite atualizar textos, imagens e informações.\nSUPORTE | Acompanhamento de verdade | Você recebe orientação para revisar, publicar e assumir a gestão do projeto.',true,true)}{field(draft,'faq','Perguntas · Pergunta | resposta','Preciso ter todo o conteúdo pronto? | Não. Podemos começar organizando sua ideia, suas referências e o material que já existe.\nConsigo atualizar o site sozinho? | Sim. Textos, imagens e informações principais ficam reunidos em um painel simples.\nO site funciona bem no celular? | Sim. Cada projeto é desenvolvido e revisado para computador, tablet e celular.\nDomínio e hospedagem estão incluídos? | A configuração é orientada conforme a necessidade do projeto.\nQuanto tempo leva para ficar pronto? | O prazo depende do tamanho do site e da disponibilidade do conteúdo.\nComo começamos? | Envie o formulário ou chame pelo WhatsApp.',true,true)}</div></section>
      <section className={styles.section}><h2>Contato e rodapé</h2><div className={styles.grid}>{field(draft,'contact_kicker','Chamada curta','06 · TEM UM PROJETO EM MENTE?')}{field(draft,'contact_title','Título','Vamos colocar sua ideia')}{field(draft,'contact_emphasis','Destaque','no ar.')}{field(draft,'contact_description','Descrição','Conte o que você precisa. Eu organizo o projeto e retorno com os próximos passos para transformar a ideia em um site com identidade.',true,true)}{field(draft,'whatsapp','WhatsApp','5516997168229')}{field(draft,'email','E-mail','gcapellari1@gmail.com')}{field(draft,'footer_tagline','Frase do rodapé','Sites com identidade. Gestão sem complicação.',true)}</div></section>
      <div className={styles.saveBar}><span>{publishedAt?'Existe uma versão publicada.':'Publique somente depois de revisar.'}</span><div><button className={styles.primary} type="submit">Salvar rascunho</button></div></div>
    </form>
    <form action={publishRootAction} className={styles.saveBar}><span>Publicar copia o último rascunho para webappcap.com.br.</span><div><Link className={styles.button} href="/owner/root/preview" target="_blank">Revisar Preview</Link><button className={styles.primary} type="submit">Publicar raiz</button></div></form>
  </div></main>;
}
