'use client';

import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {commerceLineTotal} from '@/core/commerce-promotions';
import {heroCopyStyle,heroTextStyle,heroTextMotion} from '@/core/hero-typography';
import {trackCommerceOrder} from '@/lib/commerce-order-tracking';
import type {TemplateRenderProps} from '../types';
import './bakery.css';

type Row=Record<string,unknown>;
const photo=(id:string,w=1600)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;
const defaultProducts:Row[]=[
 {title:'Pão Francês',category:'Pães',description:'Tradicional, crocante por fora e macio por dentro.',price:'R$ 1,10',image:photo('photo-1549931319-a545dcf3bc73')},
 {title:'Baguete Italiana',category:'Pães',description:'Casca crocante, fermentação lenta e miolo aerado.',price:'R$ 14,90',image:photo('photo-1546549032-9571cd6b27df')},
 {title:'Pão de Queijo',category:'Salgados',description:'Porção com 6 unidades, macio e bem queijudo.',price:'R$ 12,00',image:photo('photo-1578985545062-69928b1d9587')},
 {title:'Croissant de Manteiga',category:'Doces',description:'Folhado artesanal com massa leve e amanteigada.',price:'R$ 8,90',image:photo('photo-1555507036-ab1f4038808a')},
 {title:'Sonho de Creme',category:'Doces',description:'Massa fofinha, creme da casa e açúcar fino.',price:'R$ 7,50',image:photo('photo-1571115177098-24ec42ed204d')},
 {title:'Torta de Chocolate',category:'Doces',description:'Fatia generosa com chocolate intenso e massa úmida.',price:'R$ 13,90',image:photo('photo-1578985545062-69928b1d9587')}
];
const defaultHighlights:Row[]=[
 {tag:'Clássico da casa',title:'Pão francês crocante',description:'Casquinha fina, miolo macio e fornadas frescas ao longo do dia.',image:photo('photo-1549931319-a545dcf3bc73')},
 {tag:'Destaque',title:'Croissant amanteigado',description:'Folhado leve e dourado, perfeito com um café passado na hora.',image:photo('photo-1555507036-ab1f4038808a')},
 {tag:'Feito hoje',title:'Doces e tortas',description:'Receitas artesanais para levar ou montar sua mesa de café.',image:photo('photo-1519915028121-7d3463d20b13')}
];
export const bakerySample={products:defaultProducts,highlights:defaultHighlights,hero:photo('photo-1509440159596-0249088772ff',2000)};
const rows=(value:unknown)=>Array.isArray(value)?value.filter(v=>v&&typeof v==='object') as Row[]:[];
const val=(row:Row,key:string,fallback='')=>key in row?String(row[key]??'').trim():fallback;
const image=(value:unknown)=>typeof value==='string'?value:value&&typeof value==='object'?String((value as Row).url||''):'';
const brl=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
const instagramUrl=(value:string)=>value.startsWith('http')?value:`https://instagram.com/${value.replace(/^@/,'')}`;
const cssImage=(value:string)=>`linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.72)),url("${value.replaceAll('"','%22')}")`;

export function BakeryTemplate({project,data}:TemplateRenderProps){
 const root=useRef<HTMLDivElement>(null);
 const c=data.content,contact=data.contact;
 const name=val(data.identity,'name',project.name||'Padaria São Bento');
 const hero=image(data.media.bakery_hero)||bakerySample.hero;
 const products=useMemo(()=>Array.isArray(c.menu_items)?rows(c.menu_items):defaultProducts,[c.menu_items]);
 const highlights=useMemo(()=>Array.isArray(c.bakery_highlights)?rows(c.bakery_highlights):defaultHighlights,[c.bakery_highlights]);
 const whatsapp=val(contact,'whatsapp').replace(/\D/g,'');
 const phone=val(contact,'phone','(16) 3342-1234'),instagram=val(contact,'instagram','https://instagram.com/');
 const [cart,setCart]=useState<Record<number,number>>({}),[qty,setQty]=useState<Record<number,number>>({}),[activeCat,setActiveCat]=useState('Todos'),[current,setCurrent]=useState(0),[zoom,setZoom]=useState<{src:string;title:string}|null>(null),[mounted,setMounted]=useState(false),[mode,setMode]=useState<'retirada'|'entrega'>('retirada'),[customerName,setCustomerName]=useState(''),[customerPhone,setCustomerPhone]=useState(''),[address,setAddress]=useState(''),[note,setNote]=useState(''),[toast,setToast]=useState('');
 const key=`webappcap-bakery-cart-${project.id}`;
 const [cartReady,setCartReady]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'{}') as Record<number,number>;setCart(Object.fromEntries(Object.entries(saved).filter(([index,q])=>Number.isInteger(Number(index))&&Number(index)>=0&&Number(index)<products.length&&Number.isInteger(q)&&q>0)))}catch{/* O carrinho continua disponível nesta visita. */}setCartReady(true)},[key,products.length]);
 useEffect(()=>{if(!cartReady)return;try{localStorage.setItem(key,JSON.stringify(cart))}catch{/* O navegador pode bloquear armazenamento. */}},[key,cart,cartReady]);
 useEffect(()=>{if(!highlights.length)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const id=setInterval(()=>{if(!document.hidden&&!root.current?.querySelector('.carousel:hover, .carousel:focus-within'))setCurrent(i=>(i+1)%highlights.length)},4500);return()=>clearInterval(id)},[highlights.length]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -6% 0px'});root.current?.querySelectorAll('.section-head,.carousel,.center,.filters,.menu-list,.order').forEach(el=>{el.setAttribute('data-reveal','');observer.observe(el)});return()=>observer.disconnect()},[]);
 useEffect(()=>setMounted(true),[]);
 useEffect(()=>{if(!zoom)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setZoom(null)};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close)}},[zoom]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(id)},[toast]);
 const categories=['Todos',...new Set(products.map(p=>val(p,'category')).filter(Boolean))];
 const filtered=products.map((p,index)=>({p,index})).filter(({p})=>activeCat==='Todos'||val(p,'category')===activeCat);
 const entries=Object.entries(cart).map(([i,q])=>({index:Number(i),q,p:products[Number(i)]})).filter(x=>x.p&&x.q>0);
 const total=entries.reduce((sum,{p,q})=>sum+commerceLineTotal(p,q),0),count=entries.reduce((sum,{q})=>sum+q,0);
 const change=(index:number,delta:number)=>setCart(old=>{const next={...old},quantity=(next[index]||0)+delta;if(quantity<=0)delete next[index];else next[index]=quantity;return next});
 const sendOrder=()=>{
  if(!whatsapp||!entries.length)return;
  if(mode==='entrega'&&!address.trim()){setToast('Informe o endereço de entrega');return}
  const lines=entries.map(({p,q})=>`• ${q}x ${val(p,'title')} — ${brl(commerceLineTotal(p,q))}`);
  const delivery=mode==='retirada'?'Retirada na padaria':`Entrega em: ${address.trim()}`;
  const msg=[customerName.trim()?`Olá! Aqui é ${customerName.trim()}. Gostaria de fazer este pedido:`:'Olá! Gostaria de fazer este pedido:','',...lines,'',`Total estimado: ${brl(total)}`,'',delivery,note.trim()?`\nObservações: ${note.trim()}`:'','\nPode confirmar a disponibilidade?'].join('\n');
  if(customerName.trim().length>=2&&customerPhone.replace(/\D/g,'').length>=8)trackCommerceOrder({projectId:project.id,templateKey:'commerce-bakery-1',customerName:customerName.trim(),customerPhone,items:entries.map(({index,q})=>({productIndex:index,quantity:q}))});
  window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');
 };
 const strip=products;
 const accent=/^#[0-9a-f]{6}$/i.test(val(data.appearance,'bakery_accent'))?val(data.appearance,'bakery_accent'):'#9c4f2f';
 const titleStyle={...heroTextStyle(data.appearance,'title'),'--hero-title-custom':heroTextStyle(data.appearance,'title').fontSize||'6.6rem'} as CSSProperties;
 const eyebrowStyle={...heroTextStyle(data.appearance,'eyebrow')} as CSSProperties;
 const subtitleStyle={...heroTextStyle(data.appearance,'subtitle')} as CSSProperties;
 const phoneStyle={...heroTextStyle(data.appearance,'phone')} as CSSProperties;
 return <div ref={root} className="bakerySite js" style={{'--accent':accent,'--accent-dark':accent} as CSSProperties}>
  <nav className="nav" aria-label="Principal"><div className="container nav-in"><a className="logo" href="#topo">{name}</a><div className="nav-links"><a href="#destaques">Destaques</a><a href="#cardapio">Cardápio</a><a href="#pedido">Pedido</a><a className="cart-chip" href="#pedido">Pedido: {count} · {brl(total)}</a></div></div></nav>
  <header className="hero" id="topo" style={{backgroundImage:cssImage(hero),backgroundPosition:val((data.media.bakery_hero&&typeof data.media.bakery_hero==='object'?data.media.bakery_hero:{} ) as Row,'position','center')}}><div className="container hero-content" style={heroCopyStyle(data.appearance)}><p className="eyebrow bakeryHeroText bakeryHeroEyebrow" style={eyebrowStyle} data-hero-motion={heroTextMotion(data.appearance,'eyebrow')}>{val(c,'bakery_eyebrow','Desde 1998, com pão quente todos os dias')}</p><h1 className="bakeryHeroText bakeryHeroTitle" style={titleStyle} data-hero-motion={heroTextMotion(data.appearance,'title')}>{val(c,'bakery_hero_title',name).split('\n').map((line,i)=><span key={i}>{line}{i<val(c,'bakery_hero_title',name).split('\n').length-1?<br/>:null}</span>)}</h1><p className="hero-sub bakeryHeroText bakeryHeroSubtitle" style={subtitleStyle} data-hero-motion={heroTextMotion(data.appearance,'subtitle')}>{val(c,'bakery_hero_subtitle','Pães artesanais, salgados, doces e café fresquinho em um ambiente simples, tradicional e acolhedor.')}</p><div className="hero-actions">{whatsapp?<a className="btn btn-primary" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noopener noreferrer">Chamar no WhatsApp</a>:null}{instagram?<a className="btn btn-light" href={instagramUrl(instagram)} target="_blank" rel="noopener noreferrer">Instagram</a>:null}<a className="btn btn-ghost" href="#cardapio">Ver cardápio</a></div>{phone?<a className="phone bakeryHeroText bakeryHeroPhone" href={`tel:${phone.replace(/\D/g,'')}`} style={phoneStyle} data-hero-motion={heroTextMotion(data.appearance,'phone')}>Telefone: {phone}</a>:null}</div></header>
  {products.length?<div className="strip" aria-hidden="true"><div className="track" style={{'--strip-duration':`${Math.max(8,products.length*3)}s`} as CSSProperties}>{[0,1].map(group=><div className="group" key={group}>{strip.map((p,i)=><span className="item" key={`${group}-${i}`}>{image(p.image)?<img src={image(p.image)} alt="" width="40" height="40" loading="lazy"/>:null}{val(p,'title')}<small>{val(p,'price')}</small></span>)}</div>)}</div></div>:null}
  <main><section id="destaques"><div className="container"><div className="section-head"><div><p className="eyebrow" style={{color:'var(--accent)',opacity:1}}>{val(c,'bakery_highlights_eyebrow','Destaques da casa')}</p><h2>{val(c,'bakery_highlights_title','O que acabou\nde sair do forno').split('\n').map((s,i)=><span key={i}>{s}<br/></span>)}</h2></div><p className="section-copy">{val(c,'bakery_highlights_intro','Uma vitrine para os produtos do dia: promoções, lançamentos ou os campeões de venda.')}</p></div>
   {highlights.length?<div className="carousel" role="region" aria-roledescription="carrossel" aria-label="Destaques do dia" onPointerDown={e=>{(e.currentTarget as HTMLElement).dataset.startX=String(e.clientX)}} onPointerUp={e=>{const start=Number(e.currentTarget.dataset.startX);if(Math.abs(e.clientX-start)>50)setCurrent((current+(e.clientX<start?1:-1)+highlights.length)%highlights.length)}}><div className="slides" style={{transform:`translateX(-${current*100}%)`}}>{highlights.map((h,i)=><article className="slide" data-active={i===current} role="group" aria-roledescription="slide" aria-label={`${i+1} de ${highlights.length}`} key={i}>{image(h.image)?<img src={image(h.image)} alt="" loading={i?'lazy':'eager'}/>:null}<div className="slide-copy"><small>{val(h,'tag','Destaque')}</small><h3>{val(h,'title')}</h3><p>{val(h,'description')}</p></div></article>)}</div><div className="c-ctrl"><button className="c-btn" type="button" onClick={()=>setCurrent((current-1+highlights.length)%highlights.length)} aria-label="Destaque anterior">‹</button><div style={{display:'flex',gap:8}}>{highlights.map((h,i)=><button className="dot" type="button" key={i} aria-label={`Ir para ${val(h,'title')}`} aria-current={i===current} onClick={()=>setCurrent(i)}/>)}</div><button className="c-btn" type="button" onClick={()=>setCurrent((current+1)%highlights.length)} aria-label="Próximo destaque">›</button></div></div>:null}<div className="center"><a className="btn btn-primary" href="#cardapio">Ver o cardápio completo</a></div></div></section>
   <section id="cardapio"><div className="container"><div className="section-head"><div><p className="eyebrow" style={{color:'var(--accent)',opacity:1}}>Cardápio</p><h2>{val(c,'bakery_menu_title','Escolha e monte\nseu pedido').split('\n').map((s,i)=><span key={i}>{s}<br/></span>)}</h2></div><p className="section-copy">{val(c,'bakery_menu_intro','Toque em um item para ver a foto e escolher a quantidade.')}</p></div><div className="filters" role="group" aria-label="Filtrar por categoria">{categories.map(cat=><button className="chip" key={cat} type="button" aria-pressed={cat===activeCat} onClick={()=>setActiveCat(cat)}>{cat}</button>)}</div><div className="menu-list">{filtered.map(({p,index})=><BakeryMenuItem key={index} item={p} index={index} quantity={qty[index]||1} cartQuantity={cart[index]||0} setQuantity={delta=>setQty(old=>({...old,[index]:Math.max(1,(old[index]||1)+delta)}))} onZoom={()=>setZoom({src:image(p.image),title:val(p,'title')})} onAdd={()=>{change(index,qty[index]||1);setQty(old=>({...old,[index]:1}));setToast(`${val(p,'title')} adicionado ao pedido`)}}/>)}{!filtered.length?<p>Nenhum item nesta categoria.</p>:null}</div></div></section>
   <section id="pedido"><div className="container"><div className="order"><div className="order-top"><div><p className="eyebrow" style={{color:'#f2b89f'}}>Seu pedido</p><h2>{val(c,'bakery_order_title','Pronto para enviar')}</h2></div><small>O pedido é enviado como mensagem pelo WhatsApp.</small></div><div className="order-list" aria-live="polite">{entries.length?entries.map(({p,index,q})=><div className="order-line" key={index}><div><strong>{val(p,'title')}</strong><div className="muted">{val(p,'price')} cada</div><div className="mini"><button type="button" onClick={()=>change(index,-1)} aria-label={`Diminuir ${val(p,'title')}`}>−</button><span>{q}</span><button type="button" onClick={()=>change(index,1)} aria-label={`Aumentar ${val(p,'title')}`}>+</button></div></div><strong>{brl(commerceLineTotal(p,q))}</strong><button className="remove" type="button" onClick={()=>setCart(old=>{const next={...old};delete next[index];return next})}>Remover</button></div>):<div className="empty">Seu pedido está vazio. Escolha itens no cardápio.</div>}</div><fieldset className="seg"><legend>Como você quer receber?</legend><label><input type="radio" name="bakery-mode" checked={mode==='retirada'} onChange={()=>setMode('retirada')}/><span>Retirada na padaria</span></label><label><input type="radio" name="bakery-mode" checked={mode==='entrega'} onChange={()=>setMode('entrega')}/><span>Entrega</span></label></fieldset><div className="fields"><label>Seu nome<input value={customerName} onChange={e=>setCustomerName(e.target.value)} autoComplete="name" placeholder="Como podemos te chamar?"/></label><label>Seu telefone<input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} autoComplete="tel" inputMode="tel" placeholder="(16) 99999-9999"/></label>{mode==='entrega'?<label className="full">Endereço de entrega<input value={address} onChange={e=>setAddress(e.target.value)} autoComplete="street-address" placeholder="Rua, número, bairro"/></label>:null}<label className="full">Observações<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2} placeholder="Alguma informação extra?"/></label></div><div className="order-bottom"><div><div className="total-label">Total estimado</div><div className="total">{brl(total)}</div></div><button className="btn whatsapp-order" type="button" disabled={!entries.length||!whatsapp} onClick={sendOrder}>Enviar pelo WhatsApp</button></div></div></div></section></main>
  {mounted&&zoom?createPortal(<div className="bakeryLightbox" role="dialog" aria-modal="true" aria-label={`Foto ampliada: ${zoom.title}`} onMouseDown={event=>{if(event.target===event.currentTarget)setZoom(null)}}><figure><button className="bakeryLightboxClose" type="button" onClick={()=>setZoom(null)} aria-label="Fechar foto">×</button><img src={zoom.src} alt={zoom.title}/><figcaption>{zoom.title}</figcaption></figure></div>,document.body):null}<div className={`toast ${toast?'show':''}`} role="status" aria-live="polite">{toast}</div><footer><div className="container footer-inner"><div>© {new Date().getFullYear()} {name}</div><div>Site criado pela <a className="root" href="https://webappcap.com.br" target="_blank" rel="noopener noreferrer">WebAppCap</a>.</div></div></footer>
 </div>;
}
function BakeryMenuItem({item,index,quantity,cartQuantity,setQuantity,onZoom,onAdd}:{item:Row;index:number;quantity:number;cartQuantity:number;setQuantity:(delta:number)=>void;onZoom:()=>void;onAdd:()=>void}){
 const [open,setOpen]=useState(false),name=val(item,'title',`Produto ${index+1}`),src=image(item.image);
 return <article className={`menu-item ${open?'open':''}`} style={{animationDelay:`${Math.min(index,8)*65}ms`}}><button className="menu-row" type="button" aria-expanded={open} aria-controls={`bakery-detail-${index}`} onClick={()=>setOpen(v=>!v)}><span><span className="menu-name">{name}{cartQuantity?<span className="menu-badge">{cartQuantity} no pedido</span>:null}</span><span className="menu-desc">{val(item,'description')}</span></span><span className="menu-price">{val(item,'price','R$ 0,00')}</span><span className="menu-toggle" aria-hidden="true">+</span></button><div className="menu-detail" id={`bakery-detail-${index}`}><div><div className="detail-inner">{src?<button className="zoom" type="button" onClick={onZoom} aria-label={`Ampliar foto: ${name}`}><img src={src} alt={name} loading="lazy"/><span className="zoom-hint" aria-hidden="true">Ampliar</span></button>:<div/>}<div><h3>{name}</h3><p>{val(item,'description')}</p><div className="qty-wrap"><div className="qty"><button type="button" onClick={()=>setQuantity(-1)} aria-label="Diminuir quantidade">−</button><output aria-live="polite">{quantity}</output><button type="button" onClick={()=>setQuantity(1)} aria-label="Aumentar quantidade">+</button></div><button className="add-btn" type="button" onClick={onAdd}>Adicionar ao pedido</button></div></div></div></div></div></article>;
}
