import {visibleBuyerTestimonials,testimonialImageUrl} from '@/core/commerce-testimonials';
import {SiteImage} from '../site-image';
// Scoped styles are rendered with the section, including inside Modern's Shadow DOM.
const css=`.commerce-reviews{padding:64px 0;scroll-margin-top:100px;color:inherit}.commerce-reviews-inner{width:min(calc(100% - 30px),1180px);margin-inline:auto}.commerce-reviews header{margin-bottom:24px;max-width:680px}.commerce-reviews header small{font-size:.75rem;font-weight:800;letter-spacing:.1em;color:var(--blue,#4f89ad)}.commerce-reviews h2{font-family:var(--heading,inherit);font-size:clamp(1.8rem,3vw,2.6rem);line-height:1.15;letter-spacing:-.035em;margin:8px 0 12px}.commerce-reviews header p{margin:0;color:var(--muted,#5f6b73);line-height:1.6}.commerce-review-rail{display:grid;grid-auto-flow:column;grid-auto-columns:calc((100% - 36px)/3);gap:18px;overflow-x:auto;scroll-snap-type:x mandatory;padding:6px 2px 18px;overscroll-behavior-x:contain}.commerce-review-rail[data-single=true]{grid-auto-columns:min(100%,680px)}.commerce-review-card{display:flex;flex-direction:column;min-width:0;scroll-snap-align:start;border:1px solid var(--line,#dbe8f0);border-radius:22px;padding:22px;background:#fff;box-shadow:0 8px 24px rgba(38,81,108,.07);transition:transform .22s ease,box-shadow .22s ease}.commerce-review-image{display:block;width:100%;padding:0;border:0;background:#f3f8fb;border-radius:14px;overflow:hidden;cursor:zoom-in;margin:0;aspect-ratio:4/3}.commerce-review-image img{width:100%;height:100%;object-fit:contain;display:block}.commerce-review-rail:focus-visible,.commerce-review-image:focus-visible{outline:3px solid var(--blue,#4f89ad);outline-offset:3px}@media(hover:hover) and (pointer:fine){.commerce-review-card:hover{transform:translateY(-3px);box-shadow:0 12px 28px rgba(38,81,108,.12)}}@media(max-width:900px){.commerce-review-rail{grid-auto-columns:calc((100% - 18px)/2)}}@media(max-width:600px){.commerce-reviews{padding:40px 0}.commerce-review-rail{grid-auto-columns:88%}.commerce-review-card{padding:18px}}@media(prefers-reduced-motion:reduce){.commerce-review-card{transition:none}.commerce-review-card:hover{transform:none}}`;
export function BuyerTestimonials({content,onZoom}:{content:Record<string,unknown>;onZoom:(image:{src:string;alt:string})=>void}){
 const rows=visibleBuyerTestimonials(content);if(!rows.length)return null;
 const title=String(content.testimonials_title||'Quem comprou, conta.'),intro=String(content.testimonials_intro??'Relatos de quem já recebeu nossos produtos.');
 return <section className="commerce-reviews" id="relatos" aria-labelledby="buyer-reviews-heading"><style>{css}</style><div className="commerce-reviews-inner"><header><small>RELATOS DOS COMPRADORES</small><h2 id="buyer-reviews-heading">{title}</h2>{intro?<p>{intro}</p>:null}</header><div className="commerce-review-rail" data-single={rows.length===1} tabIndex={0} role="region" aria-label="Relatos dos compradores. Role horizontalmente para ver mais.">{rows.map((row,index)=>{const src=testimonialImageUrl(row.image),alt=`Print do feedback de comprador ${index+1}`;return <article className="commerce-review-card" key={row.id}><button type="button" className="commerce-review-image" aria-label={`Ampliar print do feedback ${index+1}`} onClick={()=>onZoom({src,alt})}><SiteImage src={src} alt={alt} sizes="(max-width:600px) 85vw, (max-width:900px) 45vw, 360px"/></button></article>})}</div></div></section>;
}
