'use client';

import Image from 'next/image';
import {Archivo_Black,Inter} from 'next/font/google';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type {TemplateRenderProps} from '../types';
import {commerceSettings,replaceCommerceCatalogTerm} from '@/core/commerce-settings';
import {commerceCategories,commerceLineTotal,commercePromoLabel} from '@/core/commerce-promotions';
import {trackCommerceOrder} from '@/lib/commerce-order-tracking';
import styles from './commerce-sales.module.css';
import polish from './commerce-sales-polish.module.css';

type Row=Record<string,unknown>;
type CartLine={id:number;productIndex:number;quantity:number};

const rows=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as Row[]:[];
const text=(record:Record<string,unknown>,key:string,fallback='')=>String(record[key]??'').trim()||fallback;
const media=(record:Record<string,unknown>,key:string,fallback='')=>{const value=record[key];return value&&typeof value==='object'&&'url' in value?String((value as {url?:unknown}).url||fallback):typeof value==='string'&&value?value:fallback};
const mediaPosition=(record:Record<string,unknown>,key:string)=>{const value=record[key];return value&&typeof value==='object'&&'position' in value?String((value as {position?:unknown}).position||'center'):'center'};
const number=(value:string)=>Number.parseFloat(value.replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.'))||0;
const brl=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const salesHeadingFont=Archivo_Black({subsets:['latin'],weight:'400',variable:'--sales-heading-font',display:'swap'});
const salesBodyFont=Inter({subsets:['latin'],weight:['400','600','700','800','900'],variable:'--sales-body-font',display:'swap'});
const imageZoom=(value:unknown)=>Math.max(50,Math.min(200,Number(value)||100))/100;

export function CommerceSalesTemplate({project,data}:TemplateRenderProps){
 const settings=commerceSettings(data.content),products=rows(data.content.menu_items),categories=commerceCategories(products),name=text(data.identity,'name',project.name||'Loja local'),tagline=text(data.content,'sales_tagline',text(data.identity,'tagline','Escolha e peça pelo WhatsApp.'));
 const whatsapp=text(data.contact,'whatsapp','').replace(/\D/g,''),logo=media(data.media,'logo'),salesHero=media(data.media,'sales_hero'),accent=text(data.appearance,'accent','#159447'),vars={'--sales-accent':accent,'--sales-logo-position':mediaPosition(data.media,'logo'),'--sales-hero-position':mediaPosition(data.media,'sales_hero'),'--sales-hero-fit':data.media.sales_hero&&typeof data.media.sales_hero==='object'&&'fit' in data.media.sales_hero?String((data.media.sales_hero as {fit?:unknown}).fit||'cover'):'cover','--sales-hero-zoom':String(imageZoom(data.media.sales_hero&&typeof data.media.sales_hero==='object'?(data.media.sales_hero as {zoom?:unknown}).zoom:100))} as CSSProperties;
 const siteRef=useRef<HTMLDivElement>(null);
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<number|null>(null),[activeCategory,setActiveCategory]=useState<string|null>(null),[zoomedImage,setZoomedImage]=useState<{src:string;alt:string}|null>(null),[cartOpen,setCartOpen]=useState(false),[quantity,setQuantity]=useState(1),[cart,setCart]=useState<CartLine[]>([]);
 const nextId=useRef(1),defaultSalesWhatsappMessage='Olá! Quero fazer um pedido na {loja}.\n\nITENS DO PEDIDO\n{itens}\n\n💰 TOTAL: {total}',defaultDirectWhatsappMessage='Olá! Visitei o site da {loja} e gostaria de informações sobre outros produtos.',salesWhatsappTemplate=text(data.content,'sales_whatsapp_message',defaultSalesWhatsappMessage),directWhatsappTemplate=text(data.content,'sales_whatsapp_direct_message',defaultDirectWhatsappMessage);
 const filtered=products.filter(item=>`${text(item,'title')} ${text(item,'description')} ${text(item,'category')}`.toLowerCase().includes(query.toLowerCase())),selectedProduct=selected===null?null:products[selected],unitTotal=selectedProduct?commerceLineTotal(selectedProduct,quantity):0,categoryProducts=activeCategory?products.filter(item=>text(item,'category')===activeCategory):[];
 const cartTotal=cart.reduce((sum,line)=>sum+commerceLineTotal(products[line.productIndex]||{},line.quantity),0),cartCount=cart.reduce((sum,line)=>sum+line.quantity,0);

 useEffect(()=>{const modal=selected!==null||activeCategory!==null||cartOpen||zoomedImage!==null;if(!modal)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSelected(null);setActiveCategory(null);setCartOpen(false);setZoomedImage(null)}};document.body.style.overflow='hidden';window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',onKey)}},[selected,activeCategory,cartOpen,zoomedImage]);
 useEffect(()=>{
  const root=siteRef.current;if(!root||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const groups=['category','product'];
  const indices=new Map<string,number>();
  const paint=(group:string)=>{
    const items=Array.from(root.querySelectorAll<HTMLElement>(`[data-live-cycle="${group}"]`));
    if(!items.length)return;
    const previous=indices.get(group)??-1;
    if(previous>=0&&items[previous])items[previous].dataset.liveActive='false';
    const next=(previous+1)%items.length;
    items[next].dataset.liveActive='true';
    indices.set(group,next);
  };
  groups.forEach(paint);
  const timer=window.setInterval(()=>{if(!document.hidden)groups.forEach(paint)},2100);
  return()=>window.clearInterval(timer);
 },[]);
 const openProduct=(index:number)=>{setSelected(index);setQuantity(1)};
 const addToCart=()=>{if(selected===null)return;setCart(current=>{const existing=current.find(line=>line.productIndex===selected);return existing?current.map(line=>line.id===existing.id?{...line,quantity:line.quantity+quantity}:line):[...current,{id:nextId.current++,productIndex:selected,quantity}]});setSelected(null)};
 const message=()=>{const itemLines=cart.map(line=>{const product=products[line.productIndex]||{},total=commerceLineTotal(product,line.quantity);return `${line.quantity}x ${text(product,'title')} — ${brl(total)}`}).join('\n');const rendered=salesWhatsappTemplate.replaceAll('{loja}',name).replaceAll('{itens}',itemLines).replaceAll('{total}',brl(cartTotal)).replace(/\n{3,}/g,'\n\n').trim();return encodeURIComponent(rendered)};
 const directMessage=()=>encodeURIComponent(directWhatsappTemplate.replaceAll('{loja}',name).trim());
 const recordOrder=()=>trackCommerceOrder({projectId:project.id,templateKey:'commerce-sales-1',total:cartTotal,items:cart.map(line=>{const product=products[line.productIndex]||{},unitPrice=number(text(product,'price'));return{name:text(product,'title',`Produto ${line.productIndex+1}`),quantity:line.quantity,unitPrice,total:commerceLineTotal(product,line.quantity)}})});

 return <div ref={siteRef} className={`${styles.site} ${polish.polish} ${salesHeadingFont.variable} ${salesBodyFont.variable}`} data-project={project.slug} data-motion-live="true" style={vars}>
  <header className={styles.header}><div className={styles.brand}><div>{logo?<Image src={logo} alt={`Logo de ${name}`} fill sizes="64px"/>:<span aria-hidden="true" style={{display:'grid',height:'100%',placeItems:'center',color:accent,fontWeight:900}}>{name.slice(0,1).toUpperCase()}</span>}</div><span><strong>{name}</strong><small>{tagline}</small></span></div></header>
  <main><section className={`${styles.intro} ${salesHero?styles.introWithCover:''}`}>{salesHero?<><div className={styles.heroCover} aria-hidden="true"><Image src={salesHero} alt="" fill priority sizes="(max-width: 1120px) 100vw, 1120px"/></div><div className={styles.heroShade}/></>:null}<div className={styles.introContent}><h1>{replaceCommerceCatalogTerm(text(data.content,'sales_menu_title',text(data.content,'menu_title','Peça do seu jeito')),settings)}</h1><p>{replaceCommerceCatalogTerm(text(data.content,'sales_menu_intro',text(data.content,'menu_intro','Escolha seus produtos e envie o pedido direto pelo WhatsApp.')),settings)}</p><label><span>Buscar no {settings.catalogLabelLower}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="O que você procura?"/></label></div></section>
   {categories.length?<section className={styles.categoryShelf} aria-label="Categorias">{categories.map((category,categoryIndex)=><button type="button" data-live-cycle="category" key={category} onClick={()=>setActiveCategory(category)}><span>{category}</span><small>{products.filter(item=>text(item,'category')===category).length} itens</small></button>)}</section>:null}
   <section className={styles.catalog} aria-label={settings.catalogLabel}>{filtered.map((item,visibleIndex)=>{const index=products.indexOf(item),description=text(item,'description'),image=text(item,'image'),title=text(item,'title',`Produto ${index+1}`);return <article className={styles.card} data-live-cycle="product" key={index}>{image?<button className={styles.imageButton} type="button" onClick={()=>setZoomedImage({src:image,alt:title})} aria-label={`Ampliar imagem de ${title}`}><div className={styles.photo}><Image src={image} alt={title} fill sizes="(max-width: 700px) 100vw, 33vw" style={{objectFit:(['cover','contain','fill'].includes(text(item,'image_fit'))?text(item,'image_fit'):'cover') as CSSProperties['objectFit'],objectPosition:text(item,'image_position','center'),transform:`scale(${imageZoom(item.image_zoom)})`}}/></div></button>:<div className={styles.photo}><span>Sem imagem</span></div>}<button className={styles.productButton} type="button" onClick={()=>openProduct(index)} aria-label={`Adicionar ${title}`}><div className={styles.cardBody}>{text(item,'category')?<small>{text(item,'category')}</small>:null}<h2>{title}</h2>{description?<p>{description}</p>:null}{commercePromoLabel(item,brl)?<em className={styles.promoBadge}>{commercePromoLabel(item,brl)}</em>:null}<footer><strong>{text(item,'price','R$ 0,00')}</strong><span>Adicionar</span></footer></div></button></article>})}{!filtered.length?<p className={styles.empty}>{products.length?'Nenhum produto encontrado.':'Cadastre produtos no editor para montar o catálogo.'}</p>:null}</section>
   <section className={styles.directCta}><div><strong>Não encontrou o que queria?</strong><span>Entre em contato diretamente pelo WhatsApp.</span></div>{whatsapp?<a href={`https://wa.me/${whatsapp}?text=${directMessage()}`} target="_blank" rel="noreferrer">Falar pelo WhatsApp ↗</a>:<span className={styles.directCtaDisabled}>Configure o WhatsApp no editor</span>}</section>
  </main>
  {cartCount?<button className={styles.floatingCart} type="button" onClick={()=>setCartOpen(true)}><span>{cartCount} {cartCount===1?'item':'itens'}</span><strong>Ver pedido · {brl(cartTotal)}</strong></button>:null}
  {activeCategory?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setActiveCategory(null)}}><section className={`${styles.modal} ${styles.categoryModal}`} role="dialog" aria-modal="true" aria-labelledby="category-title"><button className={styles.close} type="button" onClick={()=>setActiveCategory(null)} aria-label="Fechar">×</button><span className={styles.modalCategory}>CATEGORIA</span><h2 id="category-title">{activeCategory}</h2><div className={styles.categoryGrid}>{categoryProducts.map(item=>{const index=products.indexOf(item),title=text(item,'title',`Produto ${index+1}`),image=text(item,'image'),promo=commercePromoLabel(item,brl);return <article key={index}>{image?<div className={styles.categoryThumb}><Image src={image} alt={title} fill sizes="180px"/></div>:null}<div><strong>{title}</strong><span>{text(item,'price','R$ 0,00')}</span>{promo?<em>{promo}</em>:null}</div><button type="button" onClick={()=>{setActiveCategory(null);openProduct(index)}}>Adicionar</button></article>})}</div></section></div>:null}
  {zoomedImage?<div className={`${styles.backdrop} ${styles.zoomBackdrop}`} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setZoomedImage(null)}}><section className={styles.zoomModal} role="dialog" aria-modal="true" aria-label={`Imagem ampliada: ${zoomedImage.alt}`}><button className={styles.zoomClose} type="button" onClick={()=>setZoomedImage(null)} aria-label="Fechar imagem ampliada">×</button><div className={styles.zoomImage}><Image src={zoomedImage.src} alt={zoomedImage.alt} fill sizes="95vw"/></div></section></div>:null}
  {selectedProduct?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="product-title"><button className={styles.close} type="button" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><span className={styles.modalCategory}>PRODUTO</span><h2 id="product-title">{text(selectedProduct,'title')} · {text(selectedProduct,'price')}</h2>{commercePromoLabel(selectedProduct,brl)?<strong className={styles.modalPromo}>{commercePromoLabel(selectedProduct,brl)}</strong>:null}{text(selectedProduct,'description')?<p>{text(selectedProduct,'description')}</p>:null}<div className={styles.quantity}><button type="button" onClick={()=>setQuantity(value=>Math.max(1,value-1))} aria-label="Diminuir quantidade">−</button><strong>{quantity}</strong><button type="button" onClick={()=>setQuantity(value=>value+1)} aria-label="Aumentar quantidade">+</button></div><button className={styles.confirm} type="button" onClick={addToCart}>Adicionar · {brl(unitTotal)}</button></section></div>:null}
  {cartOpen?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setCartOpen(false)}}><section className={`${styles.modal} ${styles.cartModal}`} role="dialog" aria-modal="true" aria-labelledby="cart-title"><button className={styles.close} type="button" onClick={()=>setCartOpen(false)} aria-label="Fechar">×</button><h2 id="cart-title">Seu pedido</h2><div className={styles.cartLines}>{cart.map(line=>{const product=products[line.productIndex]||{},lineTotal=commerceLineTotal(product,line.quantity);return <article key={line.id}><div><strong>{line.quantity}x {text(product,'title')}</strong><b>{brl(lineTotal)}</b></div><button type="button" onClick={()=>setCart(current=>current.filter(item=>item.id!==line.id))}>Remover</button></article>})}{!cart.length?<p className={styles.empty}>Seu pedido ainda está vazio.</p>:null}</div>{cart.length?<><div className={styles.cartTotal}><span>Total</span><strong>{brl(cartTotal)}</strong></div>{whatsapp?<a className={styles.confirm} href={`https://wa.me/${whatsapp}?text=${message()}`} target="_blank" rel="noreferrer" onClick={recordOrder}>Enviar pedido pelo WhatsApp ↗</a>:<p className={styles.empty}>Configure o WhatsApp no editor para receber pedidos.</p>}</>:null}</section></div>:null}
 </div>;
}
