'use client';

import Image from 'next/image';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {commerceSettings,replaceCommerceCatalogTerm} from '@/core/commerce-settings';
import type {TemplateRenderProps} from '../types';
import {CommerceSalesTemplate} from './commerce-sales';
import complete from './commerce-complete-v2.module.css';
import styles from './commerce.module.css';
import theme from './commerce-theme.module.css';

type Row=Record<string,unknown>;
type Cart=Record<number,number>;
type Vars=CSSProperties&{'--commerce-accent'?:string;'--commerce-heading'?:string;'--commerce-body'?:string;'--commerce-hero-position'?:string;'--commerce-creator-position'?:string;'--commerce-support-font'?:string;'--commerce-support-size'?:string;'--commerce-support-weight'?:string;'--commerce-support-style'?:string;'--commerce-button-font'?:string;'--commerce-button-size'?:string;'--commerce-button-weight'?:string;'--commerce-button-style'?:string};

const rows=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as Row[]:[];
const text=(record:Record<string,unknown>,key:string,fallback='')=>String(record[key]??'').trim()||fallback;
const editableText=(record:Record<string,unknown>,key:string,fallback='')=>key in record?String(record[key]??'').trim():fallback;
const image=(record:Record<string,unknown>,key:string)=>{const value=record[key];return value&&typeof value==='object'&&'url' in value?String((value as {url?:unknown}).url||'').trim():typeof value==='string'?value.trim():''};
const imagePosition=(record:Record<string,unknown>,key:string)=>{const value=record[key];return value&&typeof value==='object'&&'position' in value?String((value as {position?:unknown}).position||'center'):'center'};
const imageFit=(record:Record<string,unknown>,key:string)=>{const value=record[key],fit=value&&typeof value==='object'&&'fit' in value?String((value as {fit?:unknown}).fit||'cover'):'cover';return ['cover','contain','fill'].includes(fit)?fit:'cover'};
const money=(value:string)=>Number.parseFloat(value.replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.'))||0;
const currency=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const instagramHref=(value:string)=>value.startsWith('http')?value:`https://instagram.com/${value.replace(/^@/,'')}`;

function ImagePlaceholder({className=''}:{className?:string}){return <div className={`${styles.imagePlaceholder} ${className}`} role="img" aria-label="Inserir imagem"><span aria-hidden="true">＋</span><strong>Inserir imagem</strong></div>}

export function CommerceTemplate(props:TemplateRenderProps){const key=text(props.data.appearance,'preview_template_key',props.project.templateKey||'commerce-main-1');return key.includes('sales')?<CommerceSalesTemplate {...props}/>:<CommerceCompleteTemplate {...props}/>}

function CommerceCompleteTemplate({project,data}:TemplateRenderProps){
 const siteRef=useRef<HTMLDivElement>(null),catalogRef=useRef<HTMLDivElement>(null);
 const name=text(data.identity,'name',project.name||'Seu comércio'),tagline=editableText(data.identity,'tagline',''),location=editableText(data.identity,'location','');
 const phone=editableText(data.contact,'phone',''),whatsapp=editableText(data.contact,'whatsapp','').replace(/\D/g,''),instagram=editableText(data.contact,'instagram',''),instagramUrl=instagram?instagramHref(instagram):'';
 const creatorInstagram=editableText(data.content,'creator_instagram',''),creatorInstagramUrl=creatorInstagram?instagramHref(creatorInstagram):'';
 const scale=text(data.appearance,'scale','normal'),hero=image(data.media,'hero'),creator=image(data.media,'creator'),menu=rows(data.content.menu_items),commerce=commerceSettings(data.content);
 const copy=(key:string,fallback:string)=>replaceCommerceCatalogTerm(editableText(data.content,key,fallback),commerce);
 const legacyCopy=(key:string,fallback:string,legacy:string[])=>{const value=copy(key,fallback);return legacy.some(item=>item.toLocaleLowerCase('pt-BR')===value.toLocaleLowerCase('pt-BR'))?fallback:value};
 const heroKicker=copy('hero_kicker',''),gallery=Array.isArray(data.media.gallery)?data.media.gallery.map(item=>typeof item==='object'&&item&&'url' in item?String((item as {url?:unknown}).url||''):typeof item==='string'?item:'').filter(Boolean).slice(-6):[];
 const [cart,setCart]=useState<Cart>({});
 const total=useMemo(()=>menu.reduce((sum,item,index)=>sum+money(text(item,'price'))*(cart[index]||0),0),[menu,cart]);
 const chosen=menu.map((item,index)=>({...item,index,quantity:cart[index]||0})).filter(item=>item.quantity>0),count=chosen.reduce((sum,item)=>sum+item.quantity,0);
 const change=(index:number,delta:number)=>setCart(current=>({...current,[index]:Math.max(0,(current[index]||0)+delta)}));
 const message=encodeURIComponent(['Olá! Quero fazer este pedido:',...chosen.map(item=>`• ${item.quantity}x ${text(item,'title')} — ${currency(money(text(item,'price'))*item.quantity)}`),`Total: ${currency(total)}`].join('\n'));
 const vars:Vars={'--commerce-accent':text(data.appearance,'accent','#96abc8'),'--commerce-heading':text(data.appearance,'heading_font','Space Grotesk'),'--commerce-body':text(data.appearance,'body_font','Inter'),'--commerce-hero-position':imagePosition(data.media,'hero'),'--commerce-creator-position':imagePosition(data.media,'creator'),'--commerce-support-font':text(data.appearance,'support_font',text(data.appearance,'body_font','Inter')),'--commerce-support-size':`${Math.max(10,Math.min(28,Number(text(data.appearance,'support_size','14'))||14))}px`,'--commerce-support-weight':text(data.appearance,'support_bold','false')==='true'?'800':'400','--commerce-support-style':text(data.appearance,'support_italic','false')==='true'?'italic':'normal','--commerce-button-font':text(data.appearance,'button_font',text(data.appearance,'body_font','Inter')),'--commerce-button-size':`${Math.max(9,Math.min(22,Number(text(data.appearance,'button_size','12'))||12))}px`,'--commerce-button-weight':text(data.appearance,'button_bold','true')==='true'?'900':'500','--commerce-button-style':text(data.appearance,'button_italic','false')==='true'?'italic':'normal'};
 useEffect(()=>{const root=siteRef.current;if(!root)return;const reveal=Array.from(root.querySelectorAll<HTMLElement>('[data-reveal]'));if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){reveal.forEach(section=>section.dataset.visible='true');return}root.dataset.motionReady='true';let observer:IntersectionObserver|undefined;const frame=requestAnimationFrame(()=>{observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).dataset.visible='true';observer?.unobserve(entry.target)}}),{threshold:.06,rootMargin:'0px 0px -5%'});reveal.forEach(section=>observer?.observe(section))});return()=>{cancelAnimationFrame(frame);observer?.disconnect()}},[]);
 const fitStyle=(item:Row):CSSProperties=>({objectFit:(['cover','contain','fill'].includes(text(item,'image_fit'))?text(item,'image_fit'):'cover') as CSSProperties['objectFit'],objectPosition:text(item,'image_position','center')});
 return <div ref={siteRef} className={`${styles.site} ${theme.palette}`} data-variant="main" data-scale={scale} data-project={project.slug} style={vars}>
  <header className={`${styles.topbar} ${theme.topbar}`}><a className={styles.wordmark} href="#inicio">{name}</a><nav aria-label="Navegação principal"><a href="#inicio">{copy('nav_home','Início')}</a><a href="#cardapio">{legacyCopy('nav_menu',commerce.catalogLabel,['Opções','Cardápio'])}</a><a href="#carrinho">{legacyCopy('nav_order','Carrinho',['Pedido','Faça seu pedido','Faça seu pedido!'])} <span>{count}</span></a><a href="#redes-sociais">Instagram</a><a href="#sobre">Sobre</a></nav><a className={styles.topbarCta} href="#cardapio">{copy('hero_discover','Ver produtos')} ↓</a></header>
  <main>
   <section className={styles.hero} id="inicio">{hero?<Image src={hero} alt={`Ambiente de ${name}`} fill priority sizes="100vw" style={{objectFit:imageFit(data.media,'hero') as CSSProperties['objectFit'],objectPosition:imagePosition(data.media,'hero')}}/>:<ImagePlaceholder className={styles.heroImagePlaceholder}/>}<div className={`${styles.heroShade} ${theme.heroShade}`}/><div className={styles.heroCopy}>{heroKicker?<span>{heroKicker}</span>:null}<h1 className={theme.heroTitle}>{name}</h1>{tagline?<p>{tagline}</p>:null}<div className={styles.heroMeta}>{location?<span>{location}</span>:null}{phone?<a href={`tel:${phone.replace(/\D/g,'')}`}>{phone}</a>:null}{whatsapp?<a className={styles.whatsapp} href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer">{copy('hero_whatsapp','Falar no WhatsApp ↗')}</a>:null}{instagram?<a className={styles.whatsapp} href={instagramUrl} target="_blank" rel="noreferrer">{copy('hero_instagram','Siga no Instagram ↗')}</a>:null}</div></div></section>
   <section className={`${styles.section} ${styles.menu}`} id="cardapio" data-reveal="left"><header className={styles.sectionHead}><h2>{copy('menu_title',commerce.catalogLabel)}</h2><p>{copy('menu_intro','Passe sobre um item ou toque para ver todos os detalhes.')}</p></header>{menu.length?<div className={complete.catalogRail}><button className={complete.catalogArrow} type="button" aria-label="Produtos anteriores" onClick={()=>catalogRef.current?.scrollBy({left:-360,behavior:'smooth'})}>←</button><div ref={catalogRef} className={complete.catalogGrid}>{menu.map((item,index)=>{const title=text(item,'title',`Item ${index+1}`),src=editableText(item,'image','');return <article className={complete.productCard} key={index}><div className={complete.productImage}>{src?<Image src={src} alt={title} fill sizes="(max-width: 620px) 76vw, 16vw" style={fitStyle(item)}/>:<ImagePlaceholder/>}</div><div className={complete.productBody}><span className={complete.productIndex}>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text(item,'description')}</p><div className={complete.productBottom}><strong>{text(item,'price','R$ 0,00')}</strong>{cart[index]?<div className={complete.productControls} aria-label={`Quantidade de ${title}`}><button type="button" onClick={()=>change(index,-1)} aria-label={`Remover uma unidade de ${title}`}>−</button><b>{cart[index]}</b><button type="button" onClick={()=>change(index,1)} aria-label={`Adicionar uma unidade de ${title}`}>+</button></div>:<button type="button" onClick={()=>change(index,1)} aria-label={`Adicionar ${title} ao carrinho`}>+</button>}</div></div></article>})}</div><button className={complete.catalogArrow} type="button" aria-label="Próximos produtos" onClick={()=>catalogRef.current?.scrollBy({left:360,behavior:'smooth'})}>→</button></div>:<div className={complete.catalogEmpty}>Cadastre os produtos para montar o catálogo.</div>}</section>
   <section className={`${styles.section} ${styles.order}`} id="carrinho" data-reveal="right"><div className={complete.cartCompact}><header className={styles.sectionHead}><h2>{legacyCopy('order_title','Carrinho',['Faça seu pedido','Faça seu pedido!','Pedido'])}</h2><p>{legacyCopy('order_intro','Confira sua compra, ajuste as quantidades e veja o valor final antes de enviar o pedido.',['Escolha os itens, ajuste as quantidades e envie tudo pelo WhatsApp.'])}</p></header><div className={complete.cartShell}><div className={complete.cartList}>{chosen.length?chosen.map(item=>{const src=editableText(item,'image','');return <article className={complete.cartItem} key={item.index}><div className={complete.cartThumb}>{src?<Image src={src} alt="" fill sizes="72px" style={fitStyle(item)}/>:<ImagePlaceholder/>}</div><div className={complete.cartInfo}><strong>{text(item,'title')}</strong><span>{text(item,'price')} cada</span></div><div className={complete.cartControls}><button type="button" onClick={()=>change(item.index,-1)} aria-label={`Remover uma unidade de ${text(item,'title')}`}>−</button><b>{item.quantity}</b><button type="button" onClick={()=>change(item.index,1)} aria-label={`Adicionar uma unidade de ${text(item,'title')}`}>+</button></div></article>}):<div className={complete.cartEmpty}>Seu carrinho ainda está vazio. <a href="#cardapio">Ver produtos →</a></div>}</div>{chosen.length&&whatsapp?<aside className={complete.cartSummary}><h3>Seu carrinho</h3>{chosen.map(item=><p key={item.index}><span>{item.quantity}× {text(item,'title')}</span><b>{currency(money(text(item,'price'))*item.quantity)}</b></p>)}<div className={complete.cartTotal}><span>Total</span><strong>{currency(total)}</strong></div><a href={`https://wa.me/${whatsapp}?text=${message}`} target="_blank" rel="noreferrer">{copy('receipt_send','Finalizar pelo WhatsApp ↗')}</a><small>{copy('receipt_notice','O estabelecimento confirmará disponibilidade, prazo e forma de pagamento.')}</small></aside>:null}</div></div>{whatsapp?<a className={complete.whatsappAfterCart} href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><span>Não encontrou o que queria?</span><strong>{copy('menu_whatsapp_cta','Peça pelo WhatsApp!')}</strong><b aria-hidden="true">→</b></a>:null}</section>
   <div className={complete.storyRow} data-reveal="left"><section className={complete.storyPanel} id="redes-sociais"><div className={complete.socialCopy}><header><span>INSTAGRAM</span><h2>{copy('social_title','Acompanhe de perto')}</h2><p>{copy('social_intro','Novidades, bastidores e criações direto no Instagram.')}</p></header>{instagram?<a className={complete.socialButton} href={instagramUrl} target="_blank" rel="noreferrer">{copy('social_follow','Siga no Instagram ↗')}</a>:null}</div><div className={complete.instagramGrid}>{Array.from({length:6},(_,index)=>gallery[index]?<div key={gallery[index]}><Image src={gallery[index]} alt={`Publicação de ${name}`} fill sizes="(max-width: 700px) 30vw, 12vw" style={{objectFit:'cover'}}/></div>:<div key={`empty-${index}`}><ImagePlaceholder/></div>)}</div></section><section className={complete.storyPanel} id="sobre"><header><span>SOBRE</span><h2>{copy('about_title',name)}</h2></header><article className={complete.creatorCompact}><div className={complete.creatorPhoto}>{creator?<Image src={creator} alt={copy('creator_name','Criadora da marca')} fill sizes="(max-width: 900px) 92vw, 18vw" style={{objectFit:imageFit(data.media,'creator') as CSSProperties['objectFit'],objectPosition:imagePosition(data.media,'creator')}}/>:<ImagePlaceholder/>}</div><div><p>{copy('about_main','')}</p><h3>{copy('creator_name','')}</h3><p>{copy('creator_bio','')}</p>{creatorInstagram?<a className={complete.creatorInstagramButton} href={creatorInstagramUrl} target="_blank" rel="noreferrer">{copy('creator_instagram_label','Siga a criadora no Instagram ↗')}</a>:null}</div></article></section></div>
  </main>
  <footer><strong>{name}</strong>{tagline?<span>{tagline}</span>:null}<a href="#inicio">{copy('footer_back','Voltar ao início ↑')}</a></footer>
 </div>;
}
