'use client';

import Image from 'next/image';
import {Archivo_Black,Caveat,Inter} from 'next/font/google';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {commerceSettings,replaceCommerceCatalogTerm} from '@/core/commerce-settings';
import {commerceHeroControls} from '@/core/commerce-hero-controls';
import {trackCommerceOrder} from '@/lib/commerce-order-tracking';
import type {TemplateRenderProps} from '../types';
import {CommerceSalesTemplate} from './commerce-sales';
import complete from './commerce-complete-v2.module.css';
import styles from './commerce.module.css';
import theme from './commerce-theme.module.css';

type Row=Record<string,unknown>;
type Cart=Record<number,number>;
type Vars=CSSProperties&{[key:`--${string}`]:string|number|undefined};

const headingFont=Archivo_Black({subsets:['latin'],weight:'400',variable:'--commerce-fixed-heading',display:'swap'});
const bodyFont=Inter({subsets:['latin'],weight:['400','500','600','700','800','900'],variable:'--commerce-fixed-body',display:'swap'});
const handwrittenFont=Caveat({subsets:['latin'],weight:['500','600'],variable:'--commerce-fixed-handwritten',display:'swap'});

const rows=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as Row[]:[];
const text=(record:Record<string,unknown>,key:string,fallback='')=>String(record[key]??'').trim()||fallback;
const editableText=(record:Record<string,unknown>,key:string,fallback='')=>key in record?String(record[key]??'').trim():fallback;
const sectionVisible=(record:Record<string,unknown>,key:string)=>!(key in record&&String(record[key]).trim().toLowerCase()==='false');
const cleanImageUrl=(value:string)=>value.includes('/commerce/commerce-')?'':value;
const image=(record:Record<string,unknown>,key:string)=>{const value=record[key],url=value&&typeof value==='object'&&'url' in value?String((value as {url?:unknown}).url||'').trim():typeof value==='string'?value.trim():'';return cleanImageUrl(url)};
const imagePosition=(record:Record<string,unknown>,key:string)=>{const value=record[key];return value&&typeof value==='object'&&'position' in value?String((value as {position?:unknown}).position||'center'):'center'};
const imageFit=(record:Record<string,unknown>,key:string)=>{const value=record[key],fit=value&&typeof value==='object'&&'fit' in value?String((value as {fit?:unknown}).fit||'cover'):'cover';return ['cover','contain','fill'].includes(fit)?fit:'cover'};
const money=(value:string)=>Number.parseFloat(value.replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.'))||0;
const currency=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const instagramHref=(value:string)=>value.startsWith('http')?value:`https://instagram.com/${value.replace(/^@/,'')}`;

function ImagePlaceholder({className=''}:{className?:string}){return <div className={`${styles.imagePlaceholder} ${className}`} role="img" aria-label="Inserir imagem"><span aria-hidden="true">＋</span><strong>Inserir imagem</strong></div>}

export function CommerceTemplate(props:TemplateRenderProps){const key=text(props.data.appearance,'preview_template_key',props.project.templateKey||'commerce-main-1');return key.includes('sales')?<CommerceSalesTemplate {...props}/>:<CommerceCompleteTemplate {...props}/>}

function CommerceCompleteTemplate({project,data}:TemplateRenderProps){
 const siteRef=useRef<HTMLDivElement>(null),catalogRef=useRef<HTMLDivElement>(null);
 const name=text(data.identity,'name',project.name||'Seu comércio'),tagline=editableText(data.identity,'tagline',''),location=editableText(data.identity,'location','');
 const phone=editableText(data.contact,'phone',''),whatsapp=editableText(data.contact,'whatsapp','').replace(/\D/g,''),instagram=editableText(data.contact,'instagram',''),instagramUrl=instagram?instagramHref(instagram):'';
 const creatorInstagram=editableText(data.content,'creator_instagram',''),creatorInstagramUrl=creatorInstagram?instagramHref(creatorInstagram):'';
 const scale=text(data.appearance,'scale','normal'),hero=image(data.media,'hero'),creator=image(data.media,'creator'),menu=rows(data.content.menu_items),commerce=commerceSettings(data.content);
 const showCatalog=sectionVisible(data.content,'show_catalog'),showCart=sectionVisible(data.content,'show_cart'),showInstagram=sectionVisible(data.content,'show_instagram'),showAbout=sectionVisible(data.content,'show_about');
 const copy=(key:string,fallback:string)=>replaceCommerceCatalogTerm(editableText(data.content,key,fallback),commerce);
 const legacyCopy=(key:string,fallback:string,legacy:string[])=>{const value=copy(key,fallback);return legacy.some(item=>item.toLocaleLowerCase('pt-BR')===value.toLocaleLowerCase('pt-BR'))?fallback:value};
 const heroKicker=copy('hero_kicker',''),gallery=Array.isArray(data.media.gallery)?data.media.gallery.map(item=>cleanImageUrl(typeof item==='object'&&item&&'url' in item?String((item as {url?:unknown}).url||''):typeof item==='string'?item:'')).filter(Boolean).slice(-6):[];
 const [cart,setCart]=useState<Cart>({}),[zoomImage,setZoomImage]=useState<{src:string;alt:string}|null>(null);
 const total=useMemo(()=>menu.reduce((sum,item,index)=>sum+money(text(item,'price'))*(cart[index]||0),0),[menu,cart]);
 const chosen=menu.map((item,index)=>({...item,index,quantity:cart[index]||0})).filter(item=>item.quantity>0),count=chosen.reduce((sum,item)=>sum+item.quantity,0);
 const change=(index:number,delta:number)=>setCart(current=>({...current,[index]:Math.max(0,(current[index]||0)+delta)}));
 const defaultOrderMessage='Olá! Quero fazer este pedido:\n\n{itens}\n\nTotal: {total}',orderTemplate=editableText(data.content,'whatsapp_order_message',defaultOrderMessage)||defaultOrderMessage,itemLines=chosen.map(item=>`• ${item.quantity}x ${text(item,'title')} — ${currency(money(text(item,'price'))*item.quantity)}`).join('\n');
 const orderMessage=orderTemplate.replaceAll('{itens}',itemLines).replaceAll('{total}',currency(total)).replaceAll('{quantidade}',String(count)).replaceAll('{loja}',name);
 const message=encodeURIComponent(orderMessage);
 const recordOrder=()=>trackCommerceOrder({projectId:project.id,templateKey:'commerce-main-1',total,items:chosen.map(item=>{const unitPrice=money(text(item,'price'));return{name:text(item,'title',`Produto ${item.index+1}`),quantity:item.quantity,unitPrice,total:unitPrice*item.quantity}})});
 const defaultDirectMessage='Olá! Visitei o site da {loja} e gostaria de informações sobre outros produtos.',directTemplate=editableText(data.content,'whatsapp_direct_message',defaultDirectMessage)||defaultDirectMessage,directMessage=encodeURIComponent(directTemplate.replaceAll('{loja}',name));
 const heroControls=commerceHeroControls(data.appearance),heroVars=Object.fromEntries(Object.entries(heroControls).map(([key,value])=>{const cssKey=`--${key.replaceAll('_','-')}`;if(key.includes('_bold_'))return[cssKey,value==='true'?'900':'400'];if(key.includes('_italic_'))return[cssKey,value==='true'?'italic':'normal'];if(key.includes('_zoom_'))return[cssKey,String((Number(value)||100)/100)];if(key.includes('_align_'))return[cssKey,value];return[cssKey,`${value}${key.includes('_size_')?'px':'%'}`]})) as Vars;
 const vars:Vars={...heroVars,'--commerce-accent':text(data.appearance,'accent','#96abc8'),'--commerce-hero-position':imagePosition(data.media,'hero'),'--commerce-hero-fit':imageFit(data.media,'hero'),'--commerce-creator-position':imagePosition(data.media,'creator'),'--commerce-support-size':`${Math.max(10,Math.min(28,Number(text(data.appearance,'support_size','14'))||14))}px`,'--commerce-support-weight':text(data.appearance,'support_bold','false')==='true'?'800':'400','--commerce-support-style':text(data.appearance,'support_italic','false')==='true'?'italic':'normal','--commerce-button-size':`${Math.max(9,Math.min(22,Number(text(data.appearance,'button_size','12'))||12))}px`,'--commerce-button-weight':text(data.appearance,'button_bold','true')==='true'?'900':'500','--commerce-button-style':text(data.appearance,'button_italic','false')==='true'?'italic':'normal'};
 useEffect(()=>{if(!zoomImage)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setZoomImage(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[zoomImage]);
 useEffect(()=>{const root=siteRef.current;if(!root)return;const reveal=Array.from(root.querySelectorAll<HTMLElement>('[data-reveal]'));root.dataset.motionReady='true';if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){reveal.forEach(section=>section.dataset.visible='true');return}let observer:IntersectionObserver|undefined,frameOne=0,frameTwo=0;frameOne=requestAnimationFrame(()=>{root.getBoundingClientRect();frameTwo=requestAnimationFrame(()=>{observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).dataset.visible='true';observer?.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -10%'});reveal.forEach(section=>observer?.observe(section))})});return()=>{cancelAnimationFrame(frameOne);cancelAnimationFrame(frameTwo);observer?.disconnect()}},[]);
 const fitStyle=(item:Row):CSSProperties=>({objectFit:(['cover','contain','fill'].includes(text(item,'image_fit'))?text(item,'image_fit'):'cover') as CSSProperties['objectFit'],objectPosition:text(item,'image_position','center')});
 return <div ref={siteRef} className={`${styles.site} ${theme.palette} ${headingFont.variable} ${bodyFont.variable} ${handwrittenFont.variable}`} data-variant="main" data-scale={scale} data-project={project.slug} style={vars}>
  <header className={styles.topbar}><a className={styles.wordmark} href="#inicio">{name}</a><nav aria-label="Navegação principal"><a href="#inicio">{copy('nav_home','Início')}</a>{showCatalog?<a href="#cardapio">{legacyCopy('nav_menu',commerce.catalogLabel,['Opções','Cardápio'])}</a>:null}{showCart?<a href="#carrinho">{legacyCopy('nav_order','Carrinho',['Pedido','Faça seu pedido','Faça seu pedido!'])} <span>{count}</span></a>:null}{showInstagram?<a href="#redes-sociais">Instagram</a>:null}{showAbout?<a href="#sobre">Sobre</a>:null}</nav>{showCatalog?<a className={styles.topbarCta} href="#cardapio">{copy('hero_discover','Ver produtos').replace(/\s*[+↓]+\s*$/,'')}</a>:null}</header>
  <main>
   <section className={styles.hero} id="inicio">{hero?<div className={styles.heroMediaFrame}><Image src={hero} alt={`Ambiente de ${name}`} width={1920} height={1080} priority sizes="100vw" className={styles.heroMedia}/></div>:<ImagePlaceholder className={styles.heroImagePlaceholder}/>}<div className={`${styles.heroShade} ${theme.heroShade}`}/><div className={styles.heroCopy}><h1 className={theme.heroTitle}>{name}</h1>{tagline?<p className={styles.heroDescriptor}>{tagline}</p>:null}{heroKicker?<p className={styles.heroSlogan}>{heroKicker}</p>:null}<div className={styles.heroMeta}>{location?<span>{location}</span>:null}{phone?<a href={`tel:${phone.replace(/\D/g,'')}`}>{phone}</a>:null}{whatsapp?<a className={styles.whatsapp} href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer">{copy('hero_whatsapp','Falar no WhatsApp ↗')}</a>:null}{instagram?<a className={styles.whatsapp} href={instagramUrl} target="_blank" rel="noreferrer">{copy('hero_instagram','Siga no Instagram ↗')}</a>:null}</div></div></section>
   {showCatalog?<section className={`${styles.section} ${styles.menu}`} id="cardapio" data-reveal="left"><header className={styles.sectionHead}><h2>{commerce.catalogLabel}</h2><p>{copy('menu_intro','Passe sobre um item ou toque para ver todos os detalhes.')}</p></header>{menu.length?<div className={complete.catalogRail}><button className={complete.catalogArrow} type="button" aria-label="Produtos anteriores" onClick={()=>catalogRef.current?.scrollBy({left:-360,behavior:'smooth'})}>←</button><div ref={catalogRef} className={complete.catalogGrid}>{menu.map((item,index)=>{const storedTitle=text(item,'title'),title=storedTitle&&!/^\d+$/.test(storedTitle)?storedTitle:`Produto ${index+1}`,src=cleanImageUrl(editableText(item,'image','')),description=editableText(item,'description','');return <article className={complete.productCard} key={index}><button className={complete.productImage} type="button" onClick={()=>src&&setZoomImage({src,alt:title})} aria-label={src?`Ampliar imagem de ${title}`:undefined} disabled={!src}>{src?<Image src={src} alt={title} fill sizes="(max-width: 620px) 76vw, 18vw" style={fitStyle(item)}/>:<ImagePlaceholder/>}</button><div className={complete.productBody}><span className={complete.productIndex}>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3>{description?<p>{description}</p>:null}<div className={complete.productBottom}><strong>{text(item,'price','R$ 0,00')}</strong>{cart[index]?<div className={complete.productControls} aria-label={`Quantidade de ${title}`}><button type="button" onClick={()=>change(index,-1)} aria-label={`Remover uma unidade de ${title}`}>−</button><b>{cart[index]}</b><button type="button" onClick={()=>change(index,1)} aria-label={`Adicionar uma unidade de ${title}`}>+</button></div>:<button type="button" onClick={()=>change(index,1)} aria-label={`Adicionar ${title} ao carrinho`}>+</button>}</div></div></article>})}</div><button className={complete.catalogArrow} type="button" aria-label="Próximos produtos" onClick={()=>catalogRef.current?.scrollBy({left:360,behavior:'smooth'})}>→</button></div>:<div className={complete.catalogEmpty}>Cadastre os produtos para montar o catálogo.</div>}{zoomImage?<div className={complete.imageLightbox} role="dialog" aria-modal="true" aria-label={`Imagem ampliada: ${zoomImage.alt}`} onClick={()=>setZoomImage(null)}><div className={complete.lightboxImage} onClick={event=>event.stopPropagation()}><img src={zoomImage.src} alt={zoomImage.alt}/><button type="button" className={complete.lightboxClose} data-lightbox-control="true" onClick={()=>setZoomImage(null)} aria-label="Fechar imagem ampliada">×</button></div></div>:null}</section>:null}
   {showCart?<section className={`${styles.section} ${styles.order}`} id="carrinho" data-reveal="right"><div className={complete.cartCompact}><div className={complete.cartSidebar}><header className={complete.cartHeading}><h2><span className={complete.cartIcon} aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 4h2l2.1 10.1a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L20 7H6M9 20h.01M17 20h.01"/></svg></span>{legacyCopy('order_title','Carrinho',['Faça seu pedido','Faça seu pedido!','Pedido'])}</h2><p>{legacyCopy('order_intro','Confira sua compra, ajuste as quantidades e veja o valor final antes de enviar o pedido.',['Escolha os itens, ajuste as quantidades e envie tudo pelo WhatsApp.'])}</p></header>{chosen.length?<aside className={complete.cartSummary}><h3>Seu carrinho</h3>{chosen.map(item=><p key={item.index}><span>{item.quantity}× {text(item,'title')}</span><b>{currency(money(text(item,'price'))*item.quantity)}</b></p>)}<div className={complete.cartTotal}><span>Total</span><strong>{currency(total)}</strong></div>{whatsapp?<a href={`https://wa.me/${whatsapp}?text=${message}`} target="_blank" rel="noreferrer" onClick={recordOrder}>{copy('receipt_send','Enviar pedido pelo WhatsApp ↗')}</a>:<span className={complete.whatsappPending}>Configure o WhatsApp no editor para receber pedidos</span>}<small>{copy('receipt_notice','O estabelecimento confirmará disponibilidade, prazo e forma de pagamento.')}</small></aside>:null}</div><div className={complete.cartMain}><div className={complete.cartList}>{chosen.length?chosen.map(item=>{const src=cleanImageUrl(editableText(item,'image','')),storedTitle=text(item,'title'),title=storedTitle&&!/^\d+$/.test(storedTitle)?storedTitle:`Produto ${item.index+1}`;return <article className={complete.cartItem} key={item.index}><div className={complete.cartThumb}>{src?<Image src={src} alt="" fill sizes="72px" style={fitStyle(item)}/>:<ImagePlaceholder/>}</div><div className={complete.cartInfo}><strong>{title}</strong><span>{text(item,'price')} cada</span></div><div className={complete.cartControls}><button type="button" onClick={()=>change(item.index,-1)} aria-label={`Remover uma unidade de ${title}`}>−</button><b>{item.quantity}</b><button type="button" onClick={()=>change(item.index,1)} aria-label={`Adicionar uma unidade de ${title}`}>+</button></div></article>}):<div className={complete.cartEmpty}>Seu carrinho ainda está vazio.{showCatalog?<a href="#cardapio">Ver produtos →</a>:null}</div>}</div>{whatsapp?<a className={complete.whatsappAfterCart} href={`https://wa.me/${whatsapp}?text=${directMessage}`} target="_blank" rel="noreferrer"><span>Não encontrou o que queria?</span><strong>Entre em contato diretamente pelo WhatsApp</strong><b aria-hidden="true">→</b></a>:<div className={`${complete.whatsappAfterCart} ${complete.whatsappPendingContact}`}><span>Não encontrou o que queria?</span><strong>Entre em contato diretamente pelo WhatsApp</strong><b aria-hidden="true">→</b></div>}</div></div></section>:null}
   {showInstagram||showAbout?<div className={`${complete.storyRow} ${showInstagram!==showAbout?complete.storyRowSingle:''}`}>{showInstagram?<section className={`${complete.storyPanel} ${complete.storyInstagram}`} id="redes-sociais" data-reveal="left"><div className={complete.socialCopy}><header><span>INSTAGRAM</span><h2>{copy('social_title','Acompanhe de perto')}</h2><p>{copy('social_intro','Novidades, bastidores e criações direto no Instagram.')}</p></header></div><div className={complete.instagramGrid}>{Array.from({length:6},(_,index)=>gallery[index]?<div key={gallery[index]}><Image src={gallery[index]} alt={`Publicação de ${name}`} fill sizes="(max-width: 700px) 30vw, 12vw" style={{objectFit:'cover'}}/></div>:<div key={`empty-${index}`}><ImagePlaceholder/></div>)}</div>{instagram?<a className={complete.socialButton} href={instagramUrl} target="_blank" rel="noreferrer">{legacyCopy('social_follow','Seguir no Instagram ↗',['Siga no Instagram','Siga no Instagram ↗'])}</a>:null}</section>:null}{showAbout?<section className={`${complete.storyPanel} ${complete.storyAbout}`} id="sobre" data-reveal="right"><header><span>SOBRE</span><h2>{legacyCopy('about_title',name,['Sobre','Feito por quem acredita nos detalhes'])}</h2></header><div className={complete.aboutCopy}>{copy('about_main','')?<p>{copy('about_main','')}</p>:null}</div><article className={complete.creatorCard}><div className={complete.creatorPhoto}>{creator?<Image src={creator} alt={copy('creator_name','Criadora da marca')} fill sizes="(max-width: 850px) 92vw, 18vw" style={{objectFit:imageFit(data.media,'creator') as CSSProperties['objectFit'],objectPosition:imagePosition(data.media,'creator')}}/>:<ImagePlaceholder/>}</div><h3>{copy('creator_name','')}</h3><p>{copy('creator_bio','')}</p>{creatorInstagram?<a className={complete.creatorInstagramButton} href={creatorInstagramUrl} target="_blank" rel="noreferrer">{legacyCopy('creator_instagram_label','Seguir no Instagram ↗',['Siga a criadora no Instagram','Siga a criadora no Instagram ↗','Seguir a criadora no Instagram ↗'])}</a>:null}</article></section>:null}</div>:null}
  </main>
  <footer><strong>{name}</strong>{tagline?<span>{tagline}</span>:null}<a href="#inicio">{copy('footer_back','Voltar ao início ↑')}</a></footer>
 </div>;
}
