'use client';

import Image from 'next/image';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type {TemplateRenderProps} from '../types';
import {commerceSettings,replaceCommerceCatalogTerm} from '@/core/commerce-settings';
import {trackCommerceOrder} from '@/lib/commerce-order-tracking';
import styles from './commerce-sales.module.css';
import polish from './commerce-sales-polish.module.css';

type Row=Record<string,unknown>;
type CartLine={id:number;productIndex:number;quantity:number};

const rows=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as Row[]:[];
const text=(record:Record<string,unknown>,key:string,fallback='')=>String(record[key]??'').trim()||fallback;
const media=(record:Record<string,unknown>,key:string,fallback='')=>{const value=record[key];return value&&typeof value==='object'&&'url' in value?String((value as {url?:unknown}).url||fallback):typeof value==='string'&&value?value:fallback};
const mediaPosition=(record:Record<string,unknown>,key:string)=>{const value=record[key];return value&&typeof value==='object'&&'position' in value?String((value as {position?:unknown}).position||'center'):'center'};
const number=(value:string)=>Number.parseFloat(value.replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.'))||0;
const brl=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);

export function CommerceSalesTemplate({project,data}:TemplateRenderProps){
 const settings=commerceSettings(data.content),products=rows(data.content.menu_items),name=text(data.identity,'name',project.name||'Loja local'),tagline=text(data.identity,'tagline','Escolha e peça pelo WhatsApp.');
 const whatsapp=text(data.contact,'whatsapp','').replace(/\D/g,''),logo=media(data.media,'logo'),accent=text(data.appearance,'accent','#159447'),vars={'--sales-accent':accent,'--sales-logo-position':mediaPosition(data.media,'logo')} as CSSProperties;
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<number|null>(null),[cartOpen,setCartOpen]=useState(false),[quantity,setQuantity]=useState(1),[cart,setCart]=useState<CartLine[]>([]);
 const nextId=useRef(1),defaultSalesWhatsappMessage='Olá! Quero fazer um pedido na {loja}.\n\nITENS DO PEDIDO\n{itens}\n\n💰 TOTAL: {total}',salesWhatsappTemplate=text(data.content,'sales_whatsapp_message',defaultSalesWhatsappMessage);
 const filtered=products.filter(item=>`${text(item,'title')} ${text(item,'description')}`.toLowerCase().includes(query.toLowerCase())),selectedProduct=selected===null?null:products[selected],unitTotal=selectedProduct?number(text(selectedProduct,'price')):0;
 const cartTotal=cart.reduce((sum,line)=>sum+number(text(products[line.productIndex]||{},'price'))*line.quantity,0),cartCount=cart.reduce((sum,line)=>sum+line.quantity,0);

 useEffect(()=>{const modal=selected!==null||cartOpen;if(!modal)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSelected(null);setCartOpen(false)}};document.body.style.overflow='hidden';window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',onKey)}},[selected,cartOpen]);
 const openProduct=(index:number)=>{setSelected(index);setQuantity(1)};
 const addToCart=()=>{if(selected===null)return;setCart(current=>{const existing=current.find(line=>line.productIndex===selected);return existing?current.map(line=>line.id===existing.id?{...line,quantity:line.quantity+quantity}:line):[...current,{id:nextId.current++,productIndex:selected,quantity}]});setSelected(null)};
 const message=()=>{const itemLines=cart.map(line=>{const product=products[line.productIndex]||{},total=number(text(product,'price'))*line.quantity;return `${line.quantity}x ${text(product,'title')} — ${brl(total)}`}).join('\n');const rendered=salesWhatsappTemplate.replaceAll('{loja}',name).replaceAll('{itens}',itemLines).replaceAll('{total}',brl(cartTotal)).replace(/\n{3,}/g,'\n\n').trim();return encodeURIComponent(rendered)};
 const recordOrder=()=>trackCommerceOrder({projectId:project.id,templateKey:'commerce-sales-1',total:cartTotal,items:cart.map(line=>{const product=products[line.productIndex]||{},unitPrice=number(text(product,'price'));return{name:text(product,'title',`Produto ${line.productIndex+1}`),quantity:line.quantity,unitPrice,total:unitPrice*line.quantity}})});

 return <div className={`${styles.site} ${polish.polish}`} data-project={project.slug} style={vars}>
  <header className={styles.header}><div className={styles.brand}><div>{logo?<Image src={logo} alt={`Logo de ${name}`} fill sizes="64px"/>:<span aria-hidden="true" style={{display:'grid',height:'100%',placeItems:'center',color:accent,fontWeight:900}}>{name.slice(0,1).toUpperCase()}</span>}</div><span><strong>{name}</strong><small>{tagline}</small></span></div><button type="button" onClick={()=>setCartOpen(true)} aria-label={`Abrir pedido com ${cartCount} itens`}>Pedido <b>{cartCount}</b></button></header>
  <main><section className={styles.intro}><span>{settings.catalogLabel.toLocaleUpperCase('pt-BR')} ONLINE</span><h1>{replaceCommerceCatalogTerm(text(data.content,'menu_title','Peça do seu jeito'),settings)}</h1><p>{replaceCommerceCatalogTerm(text(data.content,'menu_intro','Escolha seus produtos e envie o pedido direto pelo WhatsApp.'),settings)}</p><label><span>Buscar no {settings.catalogLabelLower}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="O que você procura?"/></label></section>
   <section className={styles.catalog} aria-label={settings.catalogLabel}>{filtered.map(item=>{const index=products.indexOf(item),description=text(item,'description');return <article className={styles.card} key={index}><button type="button" onClick={()=>openProduct(index)} aria-label={`Ver ${text(item,'title')}`}><div className={styles.photo}><Image src={text(item,'image','/commerce/commerce-feature.png')} alt={text(item,'title','Produto')} fill sizes="(max-width: 700px) 100vw, 33vw"/></div><div className={styles.cardBody}><h2>{text(item,'title',`Produto ${index+1}`)}</h2>{description?<p>{description}</p>:null}<footer><strong>{text(item,'price','R$ 0,00')}</strong><span>Adicionar</span></footer></div></button></article>})}{!filtered.length?<p className={styles.empty}>{products.length?'Nenhum produto encontrado.':'Cadastre produtos no editor para montar o catálogo.'}</p>:null}</section>
  </main>
  {cartCount?<button className={styles.floatingCart} type="button" onClick={()=>setCartOpen(true)}><span>{cartCount} {cartCount===1?'item':'itens'}</span><strong>Ver pedido · {brl(cartTotal)}</strong></button>:null}
  {selectedProduct?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="product-title"><button className={styles.close} type="button" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><span className={styles.modalCategory}>PRODUTO</span><h2 id="product-title">{text(selectedProduct,'title')} · {text(selectedProduct,'price')}</h2>{text(selectedProduct,'description')?<p>{text(selectedProduct,'description')}</p>:null}<div className={styles.quantity}><button type="button" onClick={()=>setQuantity(value=>Math.max(1,value-1))} aria-label="Diminuir quantidade">−</button><strong>{quantity}</strong><button type="button" onClick={()=>setQuantity(value=>value+1)} aria-label="Aumentar quantidade">+</button></div><button className={styles.confirm} type="button" onClick={addToCart}>Adicionar · {brl(unitTotal*quantity)}</button></section></div>:null}
  {cartOpen?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setCartOpen(false)}}><section className={`${styles.modal} ${styles.cartModal}`} role="dialog" aria-modal="true" aria-labelledby="cart-title"><button className={styles.close} type="button" onClick={()=>setCartOpen(false)} aria-label="Fechar">×</button><h2 id="cart-title">Seu pedido</h2><div className={styles.cartLines}>{cart.map(line=>{const product=products[line.productIndex]||{},lineTotal=number(text(product,'price'))*line.quantity;return <article key={line.id}><div><strong>{line.quantity}x {text(product,'title')}</strong><b>{brl(lineTotal)}</b></div><button type="button" onClick={()=>setCart(current=>current.filter(item=>item.id!==line.id))}>Remover</button></article>})}{!cart.length?<p className={styles.empty}>Seu pedido ainda está vazio.</p>:null}</div>{cart.length?<><div className={styles.cartTotal}><span>Total</span><strong>{brl(cartTotal)}</strong></div>{whatsapp?<a className={styles.confirm} href={`https://wa.me/${whatsapp}?text=${message()}`} target="_blank" rel="noreferrer" onClick={recordOrder}>Enviar pedido pelo WhatsApp ↗</a>:<p className={styles.empty}>Configure o WhatsApp no editor para receber pedidos.</p>}</>:null}</section></div>:null}
 </div>;
}
