backend:
  name: github
  repo: gcapella29/portfolio-gabriel_capellari
  branch: main
  base_url: https://decap-cms-oauth-vercel.vercel.app # Proxy público para autenticação

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    files:
      - file: "admin/content/dados.json"
        label: "Dados do Currículo"
        name: "dados"
        fields:
          - {label: "Nome Completo", name: "nome", widget: "string"}
          - {label: "Título Principal (Hero)", name: "titulo_hero", widget: "string"}
          - {label: "Foto do Perfil (Hero / Sobre)", name: "foto_perfil", widget: "image"}
          
          - label: "Experiências Profissionais"
            name: "experiencias"
            widget: "list"
            fields:
              - {label: "Cargo", name: "cargo", widget: "string"}
              - {label: "Empresa", name: "empresa", widget: "string"}
              - {label: "Período / Anos", name: "periodo", widget: "string"}
              - {label: "Descrição", name: "descricao", widget: "text"}

          - label: "Links do Portfólio"
            name: "portfolio"
            widget: "list"
            fields:
              - {label: "Nome do Veículo / Projeto", name: "titulo", widget: "string"}
              - {label: "Descrição Curta", name: "descricao", widget: "string"}
              - {label: "Link Externo", name: "url", widget: "string"}
