(() => {
 const cfg=window.VITRINE_SUPABASE,sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id),store=window.WebAppCapTemplateStore,ds=window.WebAppCapDesignSystem,contract=window.WebAppCapTemplateContract;
 let user=null,template=null,modules=[];const key=new URLSearchParams(location.search).get('template');const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2500)};
 async function isOwner(){const q=await sb.from('projects').select('owner_id').eq('slug',cfg.projectSlug).maybeSingle();return q.data?.owner_id===user.id}
 function renderModules(){modules.forEach((m,i)=>m.order=i);$('modules').innerHTML=modules.map((m,i)=>{const d=ds.module(m.key);return`<div class="module"><div><strong>${d?.label||m.key}</strong><small>${d?.desc||''}</small><select data-variant="${m.key}">${Object.entries(d?.variants||{}).map(([v,l])=>`<option value="${v}" ${v===m.variant?'selected':''}>${l}</option>`).join('')}</select></div><label><input type="checkbox" data-visible="${m.key}" ${m.visible?'checked':''}> Ativo</label><div class="move"><button data-up="${m.key}" ${i===0?'disabled':''}>↑</button><button data-down="${m.key}" ${i===modules.length-1?'disabled':''}>↓</button></div></div>`}).join('');document.querySelectorAll('[data-visible]').forEach(x=>x.onchange=()=>{modules.find(m=>m.key===x.dataset.visible).visible=x.checked});document.querySelectorAll('[data-variant]').forEach(x=>x.onchange=()=>{const m=modules.find(m=>m.key===x.dataset.variant);if(ds.variantAllowed(m.key,x.value))m.variant=x.value});document.querySelectorAll('[data-up]').forEach(x=>x.onclick=()=>move(x.dataset.up,-1));document.querySelectorAll('[data-down]').forEach(x=>x.onclick=()=>move(x.dataset.down,1))}
 function move(k,d){const i=modules.findIndex(m=>m.key===k),j=i+d;if(i<0||j<0||j>=modules.length)return;[modules[i],modules[j]]=[modules[j],modules[i]];renderModules()}
 function render(){document.title=`WebAppCap — ${template.name}`;$('title').textContent=template.name;$('name').value=template.name;$('description').value=template.description||'';$('chips').value=(template.chips||[]).join(', ');$('primary').value=template.theme?.colors?.primary||'#082720';$('secondary').value=template.theme?.colors?.secondary||'#0e3b2e';$('accent').value=template.theme?.colors?.accent||'#e3bb3d';$('background').value=template.theme?.colors?.background||'#f7f4ec';$('heading').value=template.theme?.typography?.heading||'Fraunces';$('bodyFont').value=template.theme?.typography?.body||'Inter';$('width').value=template.theme?.layout?.content_width||'1200';$('radius').value=template.theme?.layout?.radius||'medium';$('source').textContent=`Fonte atual: ${store.source()} · versão ${template.version||1}`;modules=(template.layout||[]).map(([key,visible,variant],order)=>({key,visible,variant,order}));renderModules()}
 $('save').onclick=async()=>{const btn=$('save');btn.disabled=true;btn.textContent='Salvando…';try{template.name=$('name').value.trim()||template.name;template.description=$('description').value.trim();template.chips=$('chips').value.split(',').map(x=>x.trim()).filter(Boolean);template.layout=modules.map(m=>[m.key,m.visible,m.variant]);template.theme=template.theme||{};template.theme.colors={...(template.theme.colors||{}),primary:$('primary').value,secondary:$('secondary').value,accent:$('accent').value,background:$('background').value};template.theme.typography={...(template.theme.typography||{}),heading:$('heading').value,body:$('bodyFont').value};template.theme.layout={...(template.theme.layout||{}),content_width:$('width').value,radius:$('radius').value};const next={...template,version:(Number(template.version)||1)+1};const check=contract?.validateTemplate(next);if(check&&!check.valid)throw new Error(`Template inválido: ${check.errors.join('; ')}`);template=await store.save(sb,next,user.id);render();toast('Template global salvo ✓ Próximos projetos usarão esta versão.')}catch(e){console.error(e);toast(e.message||'Falha ao salvar o template global.')}finally{btn.disabled=false;btn.textContent='Salvar padrão global'}};
 $('seed').onclick=async()=>{const result=await store.seedIfEmpty(sb,user.id);if(result.seeded){template=await store.get(sb,key);render();toast(`Biblioteca inicializada no Supabase ✓ ${result.count} templates`)}else if(result.error)toast(result.error.message||'Não foi possível inicializar a biblioteca.');else{template=await store.get(sb,key);render();toast(`Biblioteca já ativa · ${result.count||0} templates`)}};
 async function boot(){const session=(await sb.auth.getSession()).data.session;if(!session){location.replace('/admin/projects.html');return}user=session.user;if(!(await isOwner())){location.replace('/admin/');return}if(!key)throw new Error('Template não informado.');const seed=await store.seedIfEmpty(sb,user.id);if(seed.error)throw seed.error;template=await store.get(sb,key);if(!template)throw new Error('Template não encontrado.');$('app').classList.remove('hidden');render();if(seed.seeded)toast(`Biblioteca persistente inicializada ✓ ${seed.count} templates`)}
 boot().catch(e=>{console.error(e);$('fatal').textContent=e.message;$('fatal').classList.remove('hidden')});
})();