(() => {
 const cfg=window.VITRINE_SUPABASE,sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id),store=window.WebAppCapTemplateStore,ds=window.WebAppCapDesignSystem;
 let user=null,project=null,snapshot=null,template=null,theme=null,plan=null;const slug=()=>window.VITRINE_PROJECT_CONTEXT?.slug||null;const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2200)};
 const get=(o,p)=>p.split('.').reduce((a,k)=>a?.[k],o),set=(o,p,v)=>{const a=p.split('.');let x=o;a.slice(0,-1).forEach(k=>x=x[k]||(x[k]={}));x[a.at(-1)]=v};
 function mergeTheme(raw){const base=structuredClone(template?.theme||{}),out=base;for(const [group,value] of Object.entries(raw||{})){if(value&&typeof value==='object'&&!Array.isArray(value))out[group]={...(out[group]||{}),...structuredClone(value)};else out[group]=value}return out}
 function validOption(path,value){const map={'typography.heading':'heading','typography.body':'body','typography.scale':'scale','layout.content_width':'content_width','layout.section_spacing':'section_spacing','layout.radius':'radius','layout.density':'density','buttons.style':'buttonStyle','buttons.weight':'buttonWeight','effects.shadow':'shadow','effects.motion':'motion'},key=map[path];return !key||ds.themeOptions[key].includes(String(value))}
 function applyGuardrails(){if(!theme.guardrails?.enabled)return;const mode=theme.guardrails.palette_mode||'signature',accent=theme.colors?.accent||template.theme.colors.accent;theme.colors={...theme.colors,...ds.palette(mode,accent)}}
 function renderPalette(){const wrap=$('guardrails');if(!theme.guardrails?.enabled){wrap.classList.add('hidden');return}wrap.classList.remove('hidden');$('paletteMode').innerHTML=Object.entries(ds.palettes).map(([k,p])=>`<option value="${k}" ${theme.guardrails.palette_mode===k?'selected':''}>${p.label}</option>`).join('');$('accent').value=theme.colors.accent||'#e3bb3d';$('accentColor').value=theme.colors.accent||'#e3bb3d'}
 function renderForm(){applyGuardrails();renderPalette();document.querySelectorAll('[data-path]').forEach(el=>{const value=get(theme,el.dataset.path);if(value!=null)el.value=value});document.querySelectorAll('[data-color]').forEach(el=>{const value=get(theme,el.dataset.color);if(value)el.value=value});syncPreview()}
 function syncPreview(){applyGuardrails();const c=theme.colors||{},root=$('previewCard').style;root.setProperty('--p-primary',c.primary||'#082720');root.setProperty('--p-secondary',c.secondary||'#0e3b2e');root.setProperty('--p-accent',c.accent||'#e3bb3d');root.setProperty('--p-bg',c.background||'#f7f4ec');root.setProperty('--p-surface',c.surface||'#fff');root.setProperty('--p-text',c.text||'#171310');$('templateBadge').textContent=`${template.name} · v${template.version||1}`}
 function bind(){document.querySelectorAll('[data-path]').forEach(el=>el.oninput=()=>{if(!validOption(el.dataset.path,el.value))return;set(theme,el.dataset.path,el.value);syncPreview()});document.querySelectorAll('[data-color]').forEach(el=>el.oninput=()=>{set(theme,el.dataset.color,el.value);const text=document.querySelector(`[data-path="${el.dataset.color}"]`);if(text)text.value=el.value;syncPreview()});$('paletteMode').onchange=()=>{theme.guardrails.palette_mode=$('paletteMode').value;applyGuardrails();renderForm()};const changeAccent=v=>{theme.colors.accent=v;applyGuardrails();$('accent').value=v;$('accentColor').value=v;renderForm()};$('accent').onchange=()=>changeAccent($('accent').value);$('accentColor').oninput=()=>changeAccent($('accentColor').value)}
 $('resetButton').onclick=async()=>{const ok=await window.WebAppCapUX.confirm({title:'Restaurar aparência do template?',message:`A aparência voltará à versão atual de “${template.name}”.`,confirmText:'Restaurar aparência',danger:true});if(!ok)return;theme=structuredClone(template.theme||{});renderForm();toast('Padrão restaurado localmente. Salve para confirmar.')};
 $('saveButton').onclick=async()=>{if(plan?.limits?.advanced_theme===false)return toast('Seu plano atual não permite personalização avançada.');const btn=$('saveButton');btn.disabled=true;btn.textContent='Salvando…';try{applyGuardrails();snapshot.theme={is_visible:true,content:structuredClone(theme)};const u=await sb.from('project_drafts').update({snapshot,updated_by:user.id,updated_at:new Date().toISOString()}).eq('project_id',project.id);if(u.error)throw u.error;toast('Aparência salva no rascunho ✓')}catch(e){console.error(e);toast(e.message||'Erro ao salvar aparência.')}finally{btn.disabled=false;btn.textContent='Salvar aparência'}};
 async function boot(){const session=(await sb.auth.getSession()).data.session;if(!session)return;user=session.user;const requested=slug();if(!requested)throw new Error('Selecione um projeto.');const p=await sb.from('projects').select('*').eq('slug',requested).maybeSingle();if(p.error||!p.data)throw p.error||new Error('Projeto não encontrado.');project=p.data;const member=await sb.from('project_members').select('role').eq('project_id',project.id).eq('user_id',user.id).maybeSingle();if(!['owner','admin'].includes(member.data?.role))throw new Error('Aparência disponível somente para Owner/Admin.');const d=await sb.from('project_drafts').select('snapshot').eq('project_id',project.id).maybeSingle();if(d.error||!d.data)throw d.error||new Error('Rascunho não encontrado.');snapshot=structuredClone(d.data.snapshot||{});const key=snapshot?.template?.content?.key;template=key?await store.get(sb,key):await store.bySiteType(sb,project.site_type);if(!template)throw new Error('Template do projeto não encontrado.');theme=mergeTheme(snapshot?.theme?.content||{});const pq=await sb.from('project_commercial').select('limits,status').eq('project_id',project.id).maybeSingle();plan=pq.data||{limits:{advanced_theme:true}};$('loginView').classList.add('hidden');$('app').classList.remove('hidden');$('projectLabel').textContent=`${project.name} · padrão ${template.name} v${template.version||1}`;$('contentLink').href=`/admin/?project=${encodeURIComponent(project.slug)}`;$('structureLink').href=`/admin/structure.html?project=${encodeURIComponent(project.slug)}`;$('previewLink').href=`/preview.html?preview=draft&project=${encodeURIComponent(project.slug)}`;bind();renderForm()}
 $('loginForm').onsubmit=async e=>{e.preventDefault();const r=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(r.error)return $('err').textContent='E-mail ou senha inválidos.';boot().catch(e=>toast(e.message))};boot().catch(e=>{console.error(e);toast(e.message||'Não foi possível carregar a aparência.')});
})();