(() => {
 if(window.WebAppCapUX)return;
 const state={dirty:false};
 const root=()=>{let r=document.getElementById('webappcapUxToastRoot');if(!r){r=document.createElement('div');r.id='webappcapUxToastRoot';r.className='webappcap-ux-toast-root';document.body.appendChild(r)}return r};
 function toast(message,{type='info',duration=2600}={}){const el=document.createElement('div');el.className=`webappcap-ux-toast ${type}`;el.innerHTML=`<span class="ux-dot"></span><div>${String(message||'')}</div>`;root().appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220)},duration)}
 function setButtonBusy(button,busy,{busyText='Salvando…'}={}){if(!button)return;if(!button.dataset.uxIdleText)button.dataset.uxIdleText=button.textContent;button.disabled=!!busy;button.classList.toggle('ux-busy',!!busy);button.textContent=busy?busyText:button.dataset.uxIdleText}
 function confirmAction({title='Confirmar ação',message='Deseja continuar?',confirmText='Confirmar',cancelText='Cancelar',danger=false}={}){return new Promise(resolve=>{const o=document.createElement('div');o.className='webappcap-ux-modal-backdrop';o.innerHTML=`<div class="webappcap-ux-modal"><div class="ux-kicker">${danger?'AÇÃO SENSÍVEL':'CONFIRMAÇÃO'}</div><h3>${title}</h3><p>${message}</p><div class="ux-modal-actions"><button class="ux-btn ux-btn-ghost" data-cancel>${cancelText}</button><button class="ux-btn ${danger?'ux-btn-danger':'ux-btn-dark'}" data-confirm>${confirmText}</button></div></div>`;document.body.appendChild(o);const done=v=>{o.remove();resolve(v)};o.querySelector('[data-cancel]').onclick=()=>done(false);o.querySelector('[data-confirm]').onclick=()=>done(true);o.onclick=e=>{if(e.target===o)done(false)}})}
 function markDirty(v=true){state.dirty=!!v;document.querySelectorAll('[data-ux-dirty-indicator]').forEach(el=>{el.textContent=state.dirty?'Alterações não salvas':'Tudo salvo';el.classList.toggle('dirty',state.dirty)})}
 function friendlyError(error){const raw=String(error?.message||error||'Erro inesperado.');const l=raw.toLowerCase();if(l.includes('limite do plano')||l.includes('não está disponível neste plano'))return raw;if(l.includes('row-level security')||l.includes('rls')||l.includes('permission'))return'Você não tem permissão para realizar esta alteração.';if(l.includes('duplicate')||l.includes('unique'))return'Esse valor já está sendo usado em outro projeto.';if(l.includes('network')||l.includes('fetch'))return'Não foi possível conectar ao servidor. Verifique sua internet e tente novamente.';return raw}
 window.addEventListener('beforeunload',e=>{if(!state.dirty)return;e.preventDefault();e.returnValue=''});
 document.addEventListener('click',async e=>{const a=e.target.closest('a[href]');if(!a||!state.dirty||a.target==='_blank'||a.dataset.uxIgnoreDirty!==undefined)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;e.preventDefault();const ok=await confirmAction({title:'Sair sem salvar?',message:'Existem alterações não salvas nesta página.',confirmText:'Sair mesmo assim',danger:true});if(ok){state.dirty=false;location.href=a.href}},true);

 const isContentEditor=()=>location.pathname==='/admin/'||location.pathname==='/admin/index.html';
 const waitFor=(predicate,{timeout=8000,interval=80}={})=>new Promise((resolve,reject)=>{const started=Date.now();const tick=()=>{if(predicate())return resolve(true);if(Date.now()-started>=timeout)return reject(new Error('Tempo esgotado ao salvar o rascunho.'));setTimeout(tick,interval)};tick()});
 async function editorProject(sb){const raw=new URLSearchParams(location.search).get('project');const slug=window.WebAppCapTenantResolver?.cleanSlug(raw||window.VITRINE_PROJECT_CONTEXT?.slug);if(!slug)throw new Error('Projeto não selecionado.');const q=await sb.from('projects').select('id,slug,subdomain,custom_domain,domain_status,is_published').eq('slug',slug).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('Projeto não encontrado.');return q.data}
 function editorPublicUrl(project){const route=new URL(`/p/${encodeURIComponent(project.slug)}`,location.origin).href;const active=String(project.domain_status||'').toLowerCase()==='active';if(!active)return route;const custom=String(project.custom_domain||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/.*$/,'').replace(/\.$/,'');if(custom)return`https://${custom}/`;const sub=String(project.subdomain||'').trim().toLowerCase().replace(/[^a-z0-9-]/g,'').replace(/^-+|-+$/g,'');return sub?`https://${sub}.webappcap.com.br/`:route}
 async function installAtomicPublishing(){if(!isContentEditor()||!window.supabase||!window.VITRINE_SUPABASE)return;const confirmButton=document.getElementById('confirmPublish'),publishedLink=document.getElementById('publishedLink');if(!confirmButton)return;const cfg=window.VITRINE_SUPABASE,sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});let project;try{project=await editorProject(sb);if(publishedLink)publishedLink.href=editorPublicUrl(project)}catch(error){console.warn('[WebAppCap publishing]',error);return}
   document.addEventListener('click',async event=>{if(event.target!==confirmButton)return;event.preventDefault();event.stopImmediatePropagation();if(confirmButton.dataset.atomicBusy==='1')return;confirmButton.dataset.atomicBusy='1';setButtonBusy(confirmButton,true,{busyText:'Publicando…'});try{
     if(state.dirty){const save=document.getElementById('saveButton');if(!save)throw new Error('Não foi possível salvar o rascunho antes de publicar.');save.click();await waitFor(()=>state.dirty===false)}
     const result=await sb.rpc('publish_project_atomic',{p_project_id:project.id});if(result.error)throw result.error;
     markDirty(false);document.getElementById('publishModal')?.classList.remove('show');const status=document.getElementById('statusText');if(status)status.textContent='Publicado agora · transação concluída';toast('Site publicado com segurança ✓',{type:'success',duration:3200});
     setTimeout(()=>location.reload(),650);
   }catch(error){console.error('[WebAppCap atomic publish]',error);toast(friendlyError(error)||'Erro ao publicar.',{type:'error',duration:4200})}finally{delete confirmButton.dataset.atomicBusy;setButtonBusy(confirmButton,false)}} ,true);
 }
 setTimeout(installAtomicPublishing,0);
 window.WebAppCapUX={toast,setButtonBusy,confirm:confirmAction,markDirty,friendlyError,state};
})();