(() => {
 if(window.WebAppCapUX)return;
 const state={dirty:false};
 const root=()=>{let r=document.getElementById('webappcapUxToastRoot');if(!r){r=document.createElement('div');r.id='webappcapUxToastRoot';r.className='webappcap-ux-toast-root';document.body.appendChild(r)}return r};
 function toast(message,{type='info',duration=2600}={}){const el=document.createElement('div');el.className=`webappcap-ux-toast ${type}`;el.innerHTML=`<span class="ux-dot"></span><div>${String(message||'')}</div>`;root().appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220)},duration)}
 function setButtonBusy(button,busy,{busyText='Salvando…'}={}){if(!button)return;if(!button.dataset.uxIdleText)button.dataset.uxIdleText=button.textContent;button.disabled=!!busy;button.classList.toggle('ux-busy',!!busy);button.textContent=busy?busyText:button.dataset.uxIdleText}
 function confirmAction({title='Confirmar ação',message='Deseja continuar?',confirmText='Confirmar',cancelText='Cancelar',danger=false}={}){return new Promise(resolve=>{const o=document.createElement('div');o.className='webappcap-ux-modal-backdrop';o.innerHTML=`<div class="webappcap-ux-modal"><div class="ux-kicker">${danger?'AÇÃO SENSÍVEL':'CONFIRMAÇÃO'}</div><h3>${title}</h3><p>${message}</p><div class="ux-modal-actions"><button class="ux-btn ux-btn-ghost" data-cancel>${cancelText}</button><button class="ux-btn ${danger?'ux-btn-danger':'ux-btn-dark'}" data-confirm>${confirmText}</button></div></div>`;document.body.appendChild(o);const done=v=>{o.remove();resolve(v)};o.querySelector('[data-cancel]').onclick=()=>done(false);o.querySelector('[data-confirm]').onclick=()=>done(true);o.onclick=e=>{if(e.target===o)done(false)}})}
 function markDirty(v=true){state.dirty=!!v;document.querySelectorAll('[data-ux-dirty-indicator]').forEach(el=>{el.textContent=state.dirty?'Alterações não salvas':'Tudo salvo';el.classList.toggle('dirty',state.dirty)})}
 function friendlyError(error){const raw=String(error?.message||error||'Erro inesperado.');const l=raw.toLowerCase();if(l.includes('limite do plano')||l.includes('não está disponível neste plano'))return raw;if(l.includes('row-level security')||l.includes('rls'))return'Você não tem permissão para realizar esta alteração.';if(l.includes('duplicate')||l.includes('unique'))return'Esse valor já está sendo usado em outro projeto.';if(l.includes('network')||l.includes('fetch'))return'Não foi possível conectar ao servidor. Verifique sua internet e tente novamente.';return raw}
 window.addEventListener('beforeunload',e=>{if(!state.dirty)return;e.preventDefault();e.returnValue=''});
 document.addEventListener('click',async e=>{const a=e.target.closest('a[href]');if(!a||!state.dirty||a.target==='_blank'||a.dataset.uxIgnoreDirty!==undefined)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;e.preventDefault();const ok=await confirmAction({title:'Sair sem salvar?',message:'Existem alterações não salvas nesta página.',confirmText:'Sair mesmo assim',danger:true});if(ok){state.dirty=false;location.href=a.href}},true);
 window.WebAppCapUX={toast,setButtonBusy,confirm:confirmAction,markDirty,friendlyError,state};
})();