'use client';

import {useId,useState} from 'react';
import type {UploadedProjectImage} from '@/lib/supabase/project-image-upload';
import DraggableImagePreview from './draggable-image-preview';

type Props={projectId:string;name:string;slot:string;label:string;current?:string;currentPosition?:string;currentFit?:string;help:string;multiple?:boolean};
const fits=['cover','contain','fill'] as const;

export default function DirectImageField({projectId,name,slot,label,current='',currentPosition='center',currentFit='cover',help,multiple=false}:Props){
 const inputId=useId(),[uploaded,setUploaded]=useState<UploadedProjectImage[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[position,setPosition]=useState(currentPosition),[fit,setFit]=useState(fits.includes(currentFit as typeof fits[number])?currentFit:'cover'),[removed,setRemoved]=useState(false);
 const previews=removed?[]:multiple?uploaded.map(item=>item.url):[uploaded.at(-1)?.url||current].filter(Boolean),hasImage=Boolean(current||uploaded.length);
 const select=async(event:React.ChangeEvent<HTMLInputElement>)=>{const input=event.currentTarget,files=Array.from(input.files||[]);if(!files.length)return;setBusy(true);setError('');try{const {uploadProjectImageDirect}=await import('@/lib/supabase/project-image-upload'),results:UploadedProjectImage[]=[];for(const [index,file] of files.slice(0,multiple?12:1).entries())results.push(await uploadProjectImageDirect(projectId,file,`${slot}-${index+1}`));setUploaded(items=>multiple?[...items,...results].slice(-12):results);setRemoved(false);input.value=''}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível enviar a imagem.');input.value=''}finally{setBusy(false)}};
 return <div className="upload-card" data-uploading={busy}><strong>{label}</strong>{previews.length?<div className={multiple?'media-gallery':undefined}>{previews.map((src,index)=>multiple?<img src={src} alt={`${label} ${index+1}`} loading="lazy" decoding="async" key={src}/>:<DraggableImagePreview src={src} alt={label} position={position} fit={fit} onPositionChange={setPosition} key={src}/>)}</div>:null}<span>{help}</span><label className="action secondary" htmlFor={inputId} aria-disabled={busy}><b>{busy?'Enviando…':hasImage?'Escolher outra imagem':'Selecionar imagem'}</b></label><input id={inputId} type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple={multiple} disabled={busy} onChange={select} style={{display:'none'}}/><input type="hidden" name={name} value={JSON.stringify(multiple?uploaded:uploaded.at(-1)||null)}/>{!multiple?<><input type="hidden" name={`mediaFit:${slot}`} value={fit}/><input type="hidden" name={`mediaPosition:${slot}`} value={position}/><input type="hidden" name={`removeMedia:${slot}`} value={removed?'yes':''}/>{hasImage?<button className="action secondary" type="button" onClick={()=>setRemoved(value=>!value)}>{removed?'Restaurar foto':'Remover foto'}</button>:null}</>:null}{uploaded.length?<small role="status">Imagem enviada. Agora salve o rascunho.</small>:null}{error?<small className="form-error" role="alert">{error}</small>:null}</div>;
}
