'use client';

import {useRef} from 'react';
import {imagePlacement,imageMediaStyle,movedImagePosition} from '@/core/image-placement';
import styles from './draggable-image-preview.module.css';

export default function DraggableImagePreview({src,alt,position,fit='cover',zoom=100,aspectRatio='1 / 1',onPositionChange,onZoomChange}:{src:string;alt:string;position:string;fit?:string;zoom?:number;aspectRatio?:string;onPositionChange:(position:string)=>void;onZoomChange?:(zoom:number)=>void}){
 const frame=useRef<HTMLDivElement>(null),drag=useRef<{pointer:number;startX:number;startY:number;x:number;y:number;position:string;width:number;height:number}|null>(null),placement=imagePlacement(position);
 const update=(clientX:number,clientY:number)=>{const d=drag.current;if(!d)return;onPositionChange(movedImagePosition(d.position,d.x+(clientX-d.startX)/d.width*100,d.y+(clientY-d.startY)/d.height*100))};
 return <div ref={frame} className={`${styles.frame}${aspectRatio?` ${styles.proportional}`:""}`} style={aspectRatio?{aspectRatio}:undefined} data-editor-drag="true" role="slider" tabIndex={0} aria-label={`Posição da imagem: ${alt}`} aria-valuemin={-100} aria-valuemax={100} aria-valuenow={placement.x} aria-valuetext={`${Math.round(placement.x)}% horizontal, ${Math.round(placement.y)}% vertical`} onPointerDown={event=>{if(event.button!==0)return;const rect=event.currentTarget.getBoundingClientRect();if(!rect.width||!rect.height)return;drag.current={pointer:event.pointerId,startX:event.clientX,startY:event.clientY,x:placement.x,y:placement.y,position,width:rect.width,height:rect.height};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{if(drag.current?.pointer===event.pointerId)update(event.clientX,event.clientY)}} onPointerUp={event=>{if(drag.current?.pointer===event.pointerId){drag.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}}} onPointerCancel={()=>{drag.current=null}} onLostPointerCapture={()=>{drag.current=null}} onKeyDown={event=>{const step=event.shiftKey?10:2;let x=placement.x,y=placement.y;if(event.key==='ArrowLeft')x-=step;else if(event.key==='ArrowRight')x+=step;else if(event.key==='ArrowUp')y-=step;else if(event.key==='ArrowDown')y+=step;else if(event.key==='Home'){onPositionChange('center');event.preventDefault();return}else return;event.preventDefault();onPositionChange(movedImagePosition(position,x,y))}}>
  <img src={src} alt={alt} draggable={false} style={imageMediaStyle({position,fit,zoom})}/>
  <span className={styles.focus} style={{left:`${50+placement.x}%`,top:`${50+placement.y}%`}} aria-hidden="true"/>
  <small>Arraste livremente · setas para ajustar · Home para centralizar</small>
  <button type="button" style={{position:'absolute',right:12,bottom:48,zIndex:3}} onPointerDown={event=>event.stopPropagation()} onKeyDown={event=>event.stopPropagation()} onClick={()=>onPositionChange('center')}>Centralizar</button>
  {onZoomChange?<div className={styles.zoomControls} onPointerDown={event=>event.stopPropagation()} onKeyDown={event=>event.stopPropagation()}><button type="button" onClick={()=>onZoomChange(Math.max(50,zoom-5))} aria-label="Diminuir zoom">−</button><label>Zoom <input type="range" min="50" max="200" step="5" value={zoom} onChange={event=>onZoomChange(Number(event.target.value))}/><b>{zoom}%</b></label><button type="button" onClick={()=>onZoomChange(Math.min(200,zoom+5))} aria-label="Aumentar zoom">+</button></div>:null}
 </div>;
}
