import { resolveProjectAccess } from '@/core/session';
import { readV2Content } from '@/core/onboarding-data';
import { sectionsForSegment } from '@/core/content-schema';
import { RepeatableSections } from '@/app/setup/[slug]/[step]/repeatable-sections';
import { saveContentAction } from '../actions';

const v=(o:Record<string,unknown>,k:string)=>String(o[k]??'');
export default async function ContentPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{saved?:string}>}){
 const {slug}=await params,{saved}=await searchParams,{project}=await resolveProjectAccess(slug),data=await readV2Content(project.id),trainer=project.segment==='personal-trainer';
 const definitions=sectionsForSegment(project.segment);
 return <div className="editor-page"><header><span className="eyebrow dark-text">CONTEÚDO</span><h1>Atualize tudo o que o cliente vê.</h1><p>O conteúdo pertence ao projeto, não ao template. Textos, serviços, resultados, método, agenda e demais informações continuam disponíveis mesmo ao trocar o visual.</p></header>{saved&&<div className="notice success">Alterações salvas no rascunho.</div>}<form action={saveContentAction} className="form-stack"><input type="hidden" name="slug" value={project.slug}/>
 <section className="editor-section"><h2>Identidade</h2><div className="form-grid"><label className="field"><span>Nome exibido</span><input name="name" defaultValue={v(data.identity,'name')||project.name}/></label><label className="field"><span>Localização</span><input name="location" defaultValue={v(data.identity,'location')}/></label></div><label className="field"><span>Frase curta</span><input name="tagline" defaultValue={v(data.identity,'tagline')}/></label><label className="field"><span>Descrição</span><textarea name="description" rows={4} defaultValue={v(data.identity,'description')}/></label></section>
 <section className="editor-section"><h2>Página principal</h2><label className="field"><span>Título principal</span><textarea name="hero_title" rows={2} defaultValue={v(data.content,'hero_title')}/></label><label className="field"><span>Texto de apoio</span><textarea name="hero_text" rows={3} defaultValue={v(data.content,'hero_text')}/></label><div className="form-grid"><label className="field"><span>Oferta / serviço principal</span><textarea name="primary_offer" rows={4} defaultValue={v(data.content,'primary_offer')}/></label><label className="field"><span>Prova / frase de impacto</span><textarea name="proof" rows={4} defaultValue={v(data.content,'proof')}/></label></div><label className="field"><span>Sobre</span><textarea name="about" rows={5} defaultValue={v(data.content,'about')}/></label><label className="field"><span>Informações adicionais</span><textarea name="extra_notes" rows={4} defaultValue={v(data.content,'extra_notes')}/></label></section>
 {trainer&&<><section className="editor-section"><span className="eyebrow dark-text">FITNESS</span><h2>Dados profissionais e conversão</h2><div className="form-grid"><label className="field"><span>Especialidade / título</span><input name="trainer_specialty" defaultValue={v(data.content,'trainer_specialty')} placeholder="Personal Trainer"/></label><label className="field"><span>CREF</span><input name="trainer_cref" defaultValue={v(data.content,'trainer_cref')} placeholder="Preencha somente com o registro real"/></label></div><label className="field"><span>Título da seção de resultados</span><input name="trainer_results_title" defaultValue={v(data.content,'trainer_results_title')} placeholder="Resultados construídos com consistência"/></label><div className="form-grid"><label className="field"><span>Título da agenda</span><textarea name="trainer_schedule_title" rows={2} defaultValue={v(data.content,'trainer_schedule_title')} placeholder="Horários disponíveis"/></label><label className="field"><span>Texto da agenda</span><textarea name="trainer_schedule_text" rows={2} defaultValue={v(data.content,'trainer_schedule_text')} placeholder="Confira a agenda e encontre o melhor horário para você."/></label></div><p className="help">A agenda semanal completa, números, serviços, método e demais blocos são editados abaixo.</p></section><input type="hidden" name="trainer_services" value={v(data.content,'trainer_services')}/><input type="hidden" name="trainer_method" value={v(data.content,'trainer_method')}/><input type="hidden" name="trainer_credentials" value={v(data.content,'trainer_credentials')}/></>}
 <RepeatableSections definitions={definitions} initial={data.content}/>
 <section className="editor-section"><h2>Contato</h2><div className="form-grid"><label className="field"><span>WhatsApp</span><input name="whatsapp" defaultValue={v(data.contact,'whatsapp')}/></label><label className="field"><span>Telefone</span><input name="phone" defaultValue={v(data.contact,'phone')}/></label><label className="field"><span>E-mail</span><input name="email" type="email" defaultValue={v(data.contact,'email')}/></label><label className="field"><span>Instagram</span><input name="instagram" defaultValue={v(data.contact,'instagram')}/></label></div><label className="field"><span>Endereço</span><input name="address" defaultValue={v(data.contact,'address')}/></label><label className="field"><span>Horários / observações gerais</span><textarea name="hours" rows={3} defaultValue={v(data.contact,'hours')}/></label></section>
 <div className="sticky-save"><button className="action primary">Salvar rascunho</button></div></form></div>;
}
