-- Editable WebAppCap root and anonymous, project-isolated site analytics.

create table if not exists public.platform_root_content (
  id boolean primary key default true check (id = true),
  draft jsonb not null default '{}'::jsonb,
  published jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.platform_root_content enable row level security;

drop policy if exists "platform owner manages root content" on public.platform_root_content;
create policy "platform owner manages root content"
on public.platform_root_content for all to authenticated
using (
  exists(select 1 from public.projects p where p.slug='gabriel-capellari' and p.owner_id=auth.uid() and p.archived_at is null)
)
with check (
  exists(select 1 from public.projects p where p.slug='gabriel-capellari' and p.owner_id=auth.uid() and p.archived_at is null)
);

revoke all on public.platform_root_content from anon, authenticated;
grant select, insert, update on public.platform_root_content to authenticated;

insert into public.platform_root_content(id) values(true) on conflict(id) do nothing;

create or replace function public.webappcap_public_root_content()
returns jsonb language sql stable security definer set search_path=public
as $$ select coalesce((select published from public.platform_root_content where id=true),'{}'::jsonb); $$;
revoke all on function public.webappcap_public_root_content() from public;
grant execute on function public.webappcap_public_root_content() to anon, authenticated;

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  event_type text not null check (event_type in ('page_view','contact_click','whatsapp_click','instagram_click','linkedin_click','email_click','cv_click','external_click')),
  event_label text check (event_label is null or char_length(event_label)<=160),
  path text check (path is null or char_length(path)<=500),
  referrer_host text check (referrer_host is null or char_length(referrer_host)<=255),
  session_id text check (session_id is null or char_length(session_id)<=100),
  occurred_at timestamptz not null default now()
);

create index if not exists site_analytics_events_project_time_idx on public.site_analytics_events(project_id,occurred_at desc);
create index if not exists site_analytics_events_project_type_time_idx on public.site_analytics_events(project_id,event_type,occurred_at desc);
alter table public.site_analytics_events enable row level security;

drop policy if exists "analytics members can read" on public.site_analytics_events;
create policy "analytics members can read" on public.site_analytics_events for select to authenticated using (
  exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())
  or exists(select 1 from public.project_members pm where pm.project_id=project_id and pm.user_id=auth.uid() and lower(pm.role) in ('owner','admin'))
);
revoke all on public.site_analytics_events from anon, authenticated;
grant select on public.site_analytics_events to authenticated;

create or replace function public.webappcap_track_event(
  p_project_id uuid,p_event_type text,p_event_label text default null,p_path text default null,
  p_referrer_host text default null,p_session_id text default null
) returns boolean language plpgsql security definer set search_path=public as $$
begin
  if p_event_type not in ('page_view','contact_click','whatsapp_click','instagram_click','linkedin_click','email_click','cv_click','external_click') then return false; end if;
  if not exists(
    select 1 from public.projects p join public.project_v2_state s on s.project_id=p.id
    where p.id=p_project_id and p.is_published=true and p.archived_at is null and s.lifecycle='published'
  ) then return false; end if;
  insert into public.site_analytics_events(project_id,event_type,event_label,path,referrer_host,session_id)
  values(p_project_id,p_event_type,left(nullif(trim(p_event_label),''),160),left(nullif(trim(p_path),''),500),left(nullif(lower(trim(p_referrer_host)),''),255),left(nullif(trim(p_session_id),''),100));
  return true;
end; $$;
revoke all on function public.webappcap_track_event(uuid,text,text,text,text,text) from public;
grant execute on function public.webappcap_track_event(uuid,text,text,text,text,text) to anon, authenticated;
