create table if not exists public.commerce_orders (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  template_key text not null check (template_key in ('commerce-main-1','commerce-sales-1')),
  items jsonb not null check (jsonb_typeof(items)='array'),
  total numeric(12,2) not null default 0 check (total >= 0),
  status text not null default 'sent_to_whatsapp' check (status in ('sent_to_whatsapp','in_progress','completed','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists commerce_orders_project_time_idx
  on public.commerce_orders(project_id, created_at desc);

alter table public.commerce_orders enable row level security;

drop policy if exists "commerce order history members read" on public.commerce_orders;
create policy "commerce order history members read"
on public.commerce_orders for select to authenticated using (
  exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())
  or exists(
    select 1 from public.project_members pm
    where pm.project_id=project_id
      and pm.user_id=auth.uid()
      and lower(pm.role) in ('owner','admin')
  )
);

revoke all on public.commerce_orders from anon, authenticated;
grant select on public.commerce_orders to authenticated;

create or replace function public.submit_v2_commerce_order(
  p_project_id uuid,
  p_template_key text,
  p_items jsonb,
  p_total numeric
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_id bigint;
begin
  if p_project_id is null
     or p_template_key not in ('commerce-main-1','commerce-sales-1')
     or p_items is null
     or jsonb_typeof(p_items)<>'array'
     or p_total is null
     or p_total<0
     or p_total>10000000 then
    raise exception 'invalid commerce order payload';
  end if;

  if jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>80 then
    raise exception 'invalid commerce order items';
  end if;

  if not exists(
    select 1
    from public.projects p
    join public.project_v2_state s on s.project_id=p.id
    where p.id=p_project_id
      and p.is_published=true
      and p.archived_at is null
      and s.lifecycle='published'
      and s.segment='food-business'
  ) then
    raise exception 'project is not a published commerce site';
  end if;

  insert into public.commerce_orders(project_id,template_key,items,total)
  values(p_project_id,p_template_key,p_items,round(p_total,2))
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.submit_v2_commerce_order(uuid,text,jsonb,numeric) from public;
grant execute on function public.submit_v2_commerce_order(uuid,text,jsonb,numeric) to anon, authenticated;
