import type { SegmentKey } from './domain';
export type RepeatableField={key:string;label:string;placeholder?:string};export type RepeatableSection={key:string;label:string;description:string;fields:RepeatableField[];min?:number;max?:number};
export const universalProfile={identity:['name','tagline','description','location'],business:['hero_title','hero_text','primary_offer','proof','about'],contact:['whatsapp','phone','email','instagram','address','hours'],media:['logo','hero','gallery','hero_video']};
const commonSections:RepeatableSection[]=[{key:'services',label:'Serviços / soluções',description:'O que você oferece.',fields:[{key:'title',label:'Título'},{key:'description',label:'Descrição'}],max:24},{key:'differentials',label:'Diferenciais',description:'Motivos para escolher você ou sua organização.',fields:[{key:'title',label:'Diferencial'},{key:'description',label:'Detalhe'}],max:20},{key:'testimonials',label:'Depoimentos',description:'Provas sociais que podem ser usadas por qualquer modelo compatível.',fields:[{key:'name',label:'Nome'},{key:'role',label:'Identificação'},{key:'text',label:'Depoimento'}],max:30},{key:'faq',label:'Perguntas frequentes',description:'Dúvidas e respostas.',fields:[{key:'question',label:'Pergunta'},{key:'answer',label:'Resposta'}],max:30},{key:'gallery_items',label:'Galeria',description:'Legendas e contexto para imagens.',fields:[{key:'title',label:'Título'},{key:'description',label:'Legenda'}],max:30}];
const portfolioSections:RepeatableSection[]=[
 {key:'portfolio_languages',label:'Idiomas',description:'Selos exibidos no início do site.',fields:[{key:'country',label:'Código da bandeira',placeholder:'br, gb ou es'},{key:'label_pt',label:'Texto em português'},{key:'label_en',label:'Texto em inglês'}],max:8},
 {key:'portfolio_ticker',label:'Faixa de destaques',description:'Textos que passam continuamente na faixa amarela.',fields:[{key:'title',label:'Texto'}],max:20},
 {key:'portfolio_stats',label:'Números em destaque',description:'Indicadores exibidos logo após a abertura.',fields:[{key:'number',label:'Número'},{key:'label_pt',label:'Descrição em português'},{key:'label_en',label:'Descrição em inglês'}],max:8},
 {key:'portfolio_featured_years',label:'Anos da cobertura principal',description:'Marcos exibidos na cobertura em destaque.',fields:[{key:'label_pt',label:'Texto em português'},{key:'label_en',label:'Texto em inglês'}],max:12},
 {key:'portfolio_coverage',label:'Torneios cobertos',description:'Eventos e anos de cobertura.',fields:[{key:'event',label:'Evento'},{key:'years',label:'Anos'}],max:30},
 {key:'portfolio_links',label:'Portfólio publicado',description:'Veículos e projetos onde o trabalho pode ser encontrado.',fields:[{key:'name',label:'Nome'},{key:'description_pt',label:'Descrição em português'},{key:'description_en',label:'Descrição em inglês'},{key:'url',label:'Link'}],max:20},
 {key:'portfolio_career',label:'Experiência profissional',description:'Histórico profissional em ordem de exibição.',fields:[{key:'role_pt',label:'Cargo em português'},{key:'role_en',label:'Cargo em inglês'},{key:'years',label:'Período'},{key:'organization',label:'Organização'},{key:'description_pt',label:'Descrição em português'},{key:'description_en',label:'Descrição em inglês'}],max:30},
 {key:'portfolio_education',label:'Formação',description:'Cursos e certificações.',fields:[{key:'title_pt',label:'Formação em português'},{key:'title_en',label:'Formação em inglês'},{key:'institution',label:'Instituição / período'}],max:20},
 {key:'portfolio_skills',label:'Idiomas e ferramentas',description:'Competências exibidas na pilha de fichas.',fields:[{key:'label_pt',label:'Texto em português'},{key:'label_en',label:'Texto em inglês'}],max:30},
 {key:'portfolio_gallery_meta',label:'Legendas da galeria',description:'Ano e descrição das fotos, na mesma ordem da galeria.',fields:[{key:'year',label:'Ano'},{key:'alt_pt',label:'Descrição em português'},{key:'alt_en',label:'Descrição em inglês'}],max:12}
];
const segmentOnly:Partial<Record<SegmentKey,RepeatableSection[]>>={'personal-trainer':[
 {key:'method',label:'Método / etapas',description:'Etapas do acompanhamento ou processo.',fields:[{key:'title',label:'Etapa'},{key:'description',label:'Descrição'}],max:16},
 {key:'credentials',label:'Credenciais',description:'Formações, registros e certificações.',fields:[{key:'title',label:'Credencial'},{key:'description',label:'Instituição / detalhe'}],max:20},
 {key:'results',label:'Números / provas',description:'Métricas reais usadas como prova. Não use números que não possam ser comprovados.',fields:[{key:'title',label:'Número / dado',placeholder:'Ex.: 10+ anos'},{key:'description',label:'Contexto',placeholder:'Ex.: de experiência com acompanhamento individual'}],max:12},
 {key:'stories',label:'Histórias / transformações',description:'Casos, evoluções e histórias de clientes. Use somente informações autorizadas.',fields:[{key:'title',label:'Nome / título'},{key:'description',label:'Resumo da evolução'}],max:20},
 {key:'availability',label:'Agenda semanal',description:'Dias, horários e status de disponibilidade mostrados no site.',fields:[{key:'day',label:'Dia',placeholder:'Ex.: Segunda'},{key:'hours',label:'Horário',placeholder:'Ex.: 06:00 — 20:00'},{key:'status',label:'Status',placeholder:'aberta ou fechada'}],max:14}
],'food-business':[
 {key:'news',label:'Novidades',description:'Lançamentos e novidades com foto e chamada para o cardápio.',fields:[{key:'title',label:'Título'},{key:'description',label:'Texto'},{key:'image',label:'URL da foto'}],min:3,max:18},
 {key:'highlights',label:'Destaques',description:'Produtos ou escolhas que merecem mais atenção.',fields:[{key:'title',label:'Título'},{key:'description',label:'Texto'},{key:'image',label:'URL da foto'}],min:3,max:18},
 {key:'menu_items',label:'Cardápio',description:'Itens disponíveis para consulta e montagem do pedido.',fields:[{key:'title',label:'Nome do item'},{key:'category',label:'Categoria',placeholder:'Ex.: Pins para Crocs, Adesivos ou Promoções'},{key:'description',label:'Descrição'},{key:'price',label:'Preço',placeholder:'R$ 18,00'},{key:'promo_quantity',label:'Quantidade da promoção',placeholder:'Ex.: 2'},{key:'promo_total',label:'Preço promocional do combo',placeholder:'Ex.: R$ 40,00'},{key:'removals',label:'Ingredientes que podem ser retirados',placeholder:'Um por linha'},{key:'additions',label:'Adicionais e preços',placeholder:'Ex.: Bacon | 5,00 (um por linha)'},{key:'image',label:'URL da foto'}],min:3,max:80}
],school:[{key:'courses',label:'Cursos / programas',description:'Cursos, turmas ou programas oferecidos.',fields:[{key:'title',label:'Nome'},{key:'description',label:'Descrição'}],max:40}]};
export function sectionsForSegment(segment:SegmentKey){return segment==='portfolio'?portfolioSections:segment==='food-business'?(segmentOnly[segment]||[]):[...commonSections,...(segmentOnly[segment]||[])];}
