import { resolveProjectAccess } from '@/core/session';
import { readProjectState } from '@/core/publishing';
import { isVercelDomainAutomationConfigured } from '@/core/vercel-domains';
import { saveSettingsAction, validateDomainAction } from '../actions';

export default async function SettingsPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{saved?:string;domain?:string;vercel?:string}>}){
  const {slug}=await params,{saved,domain,vercel}=await searchParams,{project}=await resolveProjectAccess(slug),state=await readProjectState(project.id),automation=isVercelDomainAutomationConfigured();
  return <div className="editor-page"><header><span className="eyebrow dark-text">DOMÍNIO</span><h1>Endereços do site.</h1><p>Gerencie o subdomínio WebAppCap e, quando necessário, conecte um domínio próprio.</p></header>
  {saved&&<div className="notice success">Domínio salvo.</div>}{domain==='active'&&<div className="notice success">Domínio verificado e ativado.</div>}{domain==='pending'&&<div className="notice">O domínio ainda aguarda configuração ou propagação do DNS.</div>}{domain==='missing'&&<div className="notice">Salve um domínio próprio antes de validar.</div>}{vercel==='error'&&<div className="notice">O domínio foi salvo, mas a sincronização automática com a Vercel falhou. Verifique a configuração técnica.</div>}{vercel==='manual'&&state?.custom_domain&&<div className="notice">Automação Vercel ainda não configurada neste ambiente; a validação DNS manual continua disponível.</div>}
  <form action={saveSettingsAction} className="form-stack"><input type="hidden" name="slug" value={project.slug}/><section className="editor-section"><h2>Endereço principal</h2><div className="native-domain"><span>Subdomínio WebAppCap</span><div><input name="nativeSubdomain" defaultValue={state?.native_subdomain||project.slug}/><strong>.webappcap.com.br</strong></div><small>Endereço incluído no projeto e disponível após a publicação.</small></div><label className="field"><span>Domínio próprio</span><input name="customDomain" defaultValue={state?.custom_domain||''} placeholder="meusite.com.br"/><small>Status: {state?.domain_status||'unconfigured'} · Automação: {automation?'configurada':'aguardando credenciais'}</small></label><p className="help">Ao trocar ou remover um domínio próprio, o vínculo anterior também é removido da hospedagem quando a automação estiver habilitada.</p></section><div className="sticky-save"><button className="action primary">Salvar domínio</button></div></form>
  {state?.custom_domain&&state.domain_status!=='active'&&<form action={validateDomainAction} className="form-stack"><input type="hidden" name="slug" value={project.slug}/><section className="editor-section"><h2>Verificação</h2><p className="help">Depois de configurar o DNS no provedor do domínio, execute a verificação. O WebAppCap consulta a hospedagem e mantém a checagem DNS como fallback.</p><button className="action">Verificar domínio agora</button></section></form>}
  </div>
}
